### ISSUE TITLE
Could not find dependency

### ISSUE THREAD

**Issue by PaulCombal** [linuxdeploy/linuxdeploy#101]
Hello,
I just found out about this tool it looks cool! I'm running into an issue though, it won't stop throwing me the following error:
```
Deploying dependencies for ELF file AppDir/usr/bin/samrewritten 
ERROR: Could not find dependency: libsteam_api.so
```
Because samrewritten depends on libsteam_api, so this makes sense. Though I've tried copying libsteam_api.so in every folder, it just won't work, and I'll keep having the same error..

```
AppDir/
├── AppRun
├── myapp.desktop
├── myapp.png
└── usr
    ├── bin
    │   └── samrewritten
    ├── lib
    │   └── libsteam_api.so
```
Does this mean I didn't understand [this doc?](https://docs.appimage.org/reference/appdir.html?highlight=appdir#usr-subdirectory)
How can I reference the dependency manually?

Thank you so much!

**Comment by TheAssassin** [comment]
Your binary probably doesn't have any rpath (`DT_RUNPATH`) set. Therefore `ldd` can't find the file. You can check by calling `ldd usr/bin/samrewritten`, it will show you `... libsteam_api.so ... not found`, I bet.

You can work around the lack of the `DT_RUNPATH` by calling `export LD_LIBRARY_PATH=AppDir/usr/lib`. That'll make `ldd` and other tools find the binary. When linuxdeploy proceeds, it'll make sure every file will receive a `DT_RUNPATH` entry eventually.

**Comment by PaulCombal** [comment]
Thanks, that was it!
I fixed it by running the command
`$ LD_LIBRARY_PATH=AppDir/usr/lib/ ./linuxdeploy-x86_64.AppImage --appdir AppDir --output appimage`

Thanks a bunch and stay safe :)
