### ISSUE TITLE
Running in docker with --appimage-extract-and-run fails fedora 30

### ISSUE THREAD

**Issue by Peterede** [linuxdeploy/linuxdeploy#104]
I am trying to run linuxdeploy in a docker container running fedora 30 using `--appimage-extract-and-run` and it is failing with the following error:

```
linuxdeploy version 1-alpha (git commit ID 6cfa741), <local dev build> built on 2019-11-13 14:37:28 UTC
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
terminate called after throwing an instance of 'subprocess::CalledProcessError'
  what():  execve failed : No such file or directory
```

On an Ubuntu docker image the error about FUSE is still reported but the process completes and builds the app image successfully.  Can you please tell me what is causing it to fail on fedora?

**Comment by TheAssassin** [comment]
Please post how you call linuxdeploy. Please put code in code blocks.

https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by TheAssassin** [comment]
Oh, I see where the error is likely. You're using some plugin that internally uses an AppImage.

The parameter `--appimage-extract-and-run` cannot be forwarded to other AppImages. Please use the environment variable `export APPIMAGE_EXTRACT_AND_RUN=1` instead.

**Comment by Peterede** [comment]
I am calling linuxdeploy as follows with no plugin:
`./linuxdeploy-x86_64.AppImage  --appimage-extract-and-run --appdir AppDir -e myapp -i default.png -d default.desktop --output appimage`

**Comment by Peterede** [comment]
I tried export APPIMAGE_EXTRACT_AND_RUN=1 but it still fails with the same error.

**Comment by TheAssassin** [comment]
The first line tells us that linuxdeploy, the application, has been started and is running. the last two lines tell us that something linuxdeploy tried to call has failed. That must be a plugin in your `PATH` or something. I don't know about your environment, but linuxdeploy *is* working...

**Comment by TheAssassin** [comment]
Can you share a link to your repository or so so I could have a look?

**Comment by Peterede** [comment]
I used a clean docker image of fedora:30 then call:
`wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
`
Then:
`chmod +x linuxdeploy*.AppImage
`
and finally:
`./linuxdeploy-x86_64.AppImage  --appimage-extract-and-run --appdir AppDir -e myapp -i default.png -d default.desktop --output appimage
`
The app isn't actually there in this test case but it fails at the same point as when the app is there so it is failing in the extraction process before it starts using the app to gather dependencies.

**Comment by TheAssassin** [comment]
I don't see any FUSE related warnings, but I just tried something out and produced a similar error:

```sh
[root@421920ff4afb /]# ./linuxdeploy-x86_64.AppImage --appimage-extract-and-run --appdir test -e /usr/bin/wget
[... lots of extract log ...]
linuxdeploy version 1-alpha (git commit ID 6cfa741), <local dev build> built on 2019-11-13 14:37:28 UTC
terminate called after throwing an instance of 'subprocess::CalledProcessError'
  what():  execve failed : No such file or directory
```

I retried with `-v0`, that showed me that there was a plugin search ongoing, and after it seemingly finished, it failed with that error message. So I tried again, this time just listing the plugins (i.e., making sure this part works) using `--list-plugins`. No error this time.

My guess: it's calling some tool it assumes to be present, but that tool is missing. Now, that subprocess library could be *more* useful and just show the tool that it hasn't been able to call. I'll check the code.

**Comment by TheAssassin** [comment]
The problem is the lack of the `which` CLI tool. It's not part of the bourne shell nor bash. However, there are alternatives, e.g., `command -v`. The problem of finding a tool in `$PATH` is quite complex, it seems. See e.g., https://unix.stackexchange.com/a/85250.

I think I'm going to build my own cheap `which`, as I did for some other tools previously. I really think there is a need for a central library that provides an API handling these chores for one, with standard C++ and without any dependencies...

**Comment by TheAssassin** [comment]
@Peterede by the way, I *have* to ask (please don't see it as an excuse for the bug; I'm fixing it right now): Why the heck are you trying to build AppImages on such a new distribution? You should reconsider building on an older system. Please see https://docs.appimage.org/introduction/concepts.html#build-on-old-systems-run-on-newer-systems for more information.

**Comment by TheAssassin** [comment]
As I don't have too much time I pushed a quick fix. Please let me know if it helps. It works in my tests just fine.

**Comment by Peterede** [comment]
> @Peterede by the way, I _have_ to ask (please don't see it as an excuse for the bug; I'm fixing it right now): Why the heck are you trying to build AppImages on such a new distribution? You should reconsider building on an older system. Please see https://docs.appimage.org/introduction/concepts.html#build-on-old-systems-run-on-newer-systems for more information.

We are building with Qt, older OS versions have very old packages available and it is not practical to install Qt from a zip as this is too large and time consuming.  We are building on a CI machine which re-installs everything each build.

**Comment by TheAssassin** [comment]
However, your AppImage won't run on the majority of systems, which is highly problematic.

If it's all about Qt only, how about building on Ubuntu xenial with the Qt PPAs provided by Stephan Binner? https://launchpad.net/~beineri/+archive/ubuntu/opt-qt-5.12.3-xenial

**Comment by Peterede** [comment]
Where can I get the latest build with the fix?  https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage returns a build from 5 days ago.

**Comment by TheAssassin** [comment]
The build failed as CentOS 6 doesn't like the quickfix... writing my own `which` now. Please give me a few more minutes.

**Comment by TheAssassin** [comment]
New build is available.

**Comment by Peterede** [comment]
This is working for me now, thank you very much.

**Comment by TheAssassin** [comment]
Thanks for your feedback.

**Comment by Peterede** [comment]
The same problem also occurs with linuxdeploy-plugin-qt-x86_64.AppImage --appimage-extract-and-run --appdir AppDir

terminate called after throwing an instance of 'subprocess::CalledProcessError'
what():  execve failed : No such file or directory

Can you please provide the same fix for this AppImage?

**Comment by TheAssassin** [comment]
We should probably open an issue there then.
