### ISSUE TITLE
Improve support for bundling apps not installed in the system

### ISSUE THREAD

**Issue by IoriBranford** [linuxdeploy/linuxdeploy#105]
1. Build an application comprised of executable and library - in this example https://bitbucket.org/rude/love
2. Install the application somewhere other than the system (/usr, /usr/local, etc.) - like AppDir/usr
3. linuxdeploy --appdir AppDir

Some steps of the bundling process assume the application is installed in the system.
1. Executable's built libraries are in AppDir/usr/lib but not found, unless I set LD_LIBRARY_PATH=AppDir/usr/lib
2. When deploying symlink, forgets about the executable in AppDir/usr/bin and looks in the system. Adding AppDir/usr/bin to $PATH doesn't get around this. The only way is installing the application to the system.

**Comment by TheAssassin** [comment]
> ecutable's built libraries are in AppDir/usr/lib but not found, unless I set

What do you mean? Does linuxdeploy not find the dependencies, or is there an error when running the built AppImage?

> When deploying symlink, forgets about the executable in AppDir/usr/bin and looks in the system. Adding AppDir/usr/bin to $PATH doesn't get around this. The only way is installing the application to the system.

I have no idea what you mean.

Please post a log or commands or anything. Your issue title makes no sense to me reading the text. I really need more information to figure out what you request.

**Comment by IoriBranford** [comment]
Here is the process I followed. (I do this because I don't want to install anything in my system except packages from a repository.)
1. Build linuxdeploy
1. Build project, install to an AppDir
```
$ hg clone -r 11.3 https://bitbucket.org/rude/love
$ cd love
$ platform/unix/automagic && ./configure --prefix=$HOME/love-11.3-armhf && make install
...
 /bin/mkdir -p '/home/pi/love-11.3-armhf/lib'
 /bin/bash ../libtool   --mode=install /usr/bin/install -c   liblove.la '/home/pi/love-11.3-armhf/lib'
libtool: install: /usr/bin/install -c .libs/liblove-11.3.so /home/pi/love-11.3-armhf/lib/liblove-11.3.so
libtool: install: (cd /home/pi/love-11.3-armhf/lib && { ln -s -f liblove-11.3.so liblove.so || { rm -f liblove.so && ln -s liblove-11.3.so liblove.so; }; })
libtool: install: /usr/bin/install -c .libs/liblove.lai /home/pi/love-11.3-armhf/lib/liblove.la
libtool: warning: remember to run 'libtool --finish /usr/lib'
 /bin/mkdir -p '/home/pi/love-11.3-armhf/bin'
  /bin/bash ../libtool   --mode=install /usr/bin/install -c love '/home/pi/love-11.3-armhf/bin'
libtool: install: /usr/bin/install -c .libs/love /home/pi/love-11.3-armhf/bin/love
...
 /bin/mkdir -p '/home/pi/love-11.3-armhf/share/applications'
 /usr/bin/install -c -m 644 platform/unix/love.desktop '/home/pi/love-11.3-armhf/share/applications'
 /bin/mkdir -p '/home/pi/love-11.3-armhf/share/icons/hicolor/scalable/mimetypes'
 /usr/bin/install -c -m 644 platform/unix/application-x-love-game.svg '/home/pi/love-11.3-armhf/share/icons/hicolor/scalable/mimetypes'
 /bin/mkdir -p '/home/pi/love-11.3-armhf/share/mime/packages'
 /usr/bin/install -c -m 644 platform/unix/love.xml '/home/pi/love-11.3-armhf/share/mime/packages'
 /bin/mkdir -p '/home/pi/love-11.3-armhf/share/pixmaps'
 /usr/bin/install -c -m 644 platform/unix/love.svg '/home/pi/love-11.3-armhf/share/pixmaps'
 /bin/mkdir -p '/home/pi/love-11.3-armhf/share/man/man1'
 /usr/bin/install -c -m 644 'platform/unix/love.6' '/home/pi/love-11.3-armhf/share/man/man1/love.1'
...
```

3. Try linuxdeploy
```
$ cd ~
$ linuxdeploy --appdir love-11.3-armhf
linuxdeploy version 1-alpha (git commit ID c45cd46), <local dev build> built on 2019-11-20 20:36:00 UTC

-- Creating basic AppDir structure -- 
Creating directory love-11.3-armhf/usr/bin/ 
Creating directory love-11.3-armhf/usr/lib/ 
Creating directory love-11.3-armhf/usr/share/applications/ 
Creating directory love-11.3-armhf/usr/share/icons/hicolor/ 
Creating directory love-11.3-armhf/usr/share/icons/hicolor/16x16/apps/ 
Creating directory love-11.3-armhf/usr/share/icons/hicolor/32x32/apps/ 
Creating directory love-11.3-armhf/usr/share/icons/hicolor/64x64/apps/ 
Creating directory love-11.3-armhf/usr/share/icons/hicolor/128x128/apps/ 
Creating directory love-11.3-armhf/usr/share/icons/hicolor/256x256/apps/ 
Creating directory love-11.3-armhf/usr/share/icons/hicolor/scalable/apps/ 

-- Deploying dependencies for existing files in AppDir -- 
Deploying dependencies for ELF file love-11.3-armhf/usr/bin/love 
ERROR: Could not find dependency: liblove-11.3.so 
ERROR: Failed to deploy dependencies for existing files
```
But liblove-11.3.so does exist in love-11.3-armhf/usr/lib since I installed it there.

4. Try again with LD_LIBRARY_PATH to find liblove-11.3.so
```
$ LD_LIBRARY_PATH=love-11.3-armhf/usr/lib linuxdeploy --appdir love-11.3-armhf
linuxdeploy version 1-alpha (git commit ID c45cd46), <local dev build> built on 2019-11-20 20:36:00 UTC

-- Creating basic AppDir structure -- 
...

-- Deploying dependencies for existing files in AppDir -- 
... (this part now works properly)

-- Copying files into AppDir -- 
...

-- Copying files into AppDir -- 

-- Deploying files into AppDir root directory -- 
WARNING: No desktop file specified, using first desktop file found: love-11.3-armhf/usr/share/applications/love.desktop 
Deploying files to AppDir root using desktop file: love-11.3-armhf/usr/share/applications/love.desktop 
Deploying desktop file to AppDir root: love-11.3-armhf/usr/share/applications/love.desktop 
Creating symlink for file love-11.3-armhf/usr/share/applications/love.desktop in/as love-11.3-armhf/ 
Deploying icon to AppDir root: love-11.3-armhf/usr/share/pixmaps/love.svg 
Creating symlink for file love-11.3-armhf/usr/share/pixmaps/love.svg in/as love-11.3-armhf/ 
ERROR: Could not deploy symlink for executable: could not find suitable executable for Exec entry: /usr/bin/love 
```

**Comment by TheAssassin** [comment]
First of all, you'd have an easier life using CMake. Also, you should use `make install DESTDIR=AppDir`. See the CMake copy and paste example: https://docs.appimage.org/packaging-guide/from-source/native-binaries.html#using-cmake-and-make-install

The problem with the installation is it's basically incomplete. It relies solely on hardcoded paths. linuxdeploy fixes this using so-called rpaths, however those are missing at first. I always recommend to patch the build system to set valid rpaths already during installation, which makes the application relocatable without linuxdeploy already.

I think we could (and maybe we really should) `export LD_LIBRARY_PATH=AppDir:"$LD_LIBRARY_PATH"` in linuxdeploy so you don't have to do that manually. That'll make your life easier, and linuxdeploy patches the files anyway in the end to contain a valid rpath.

**Comment by TheAssassin** [comment]
Your title still doesn't make sense. linuxdeploy is not about bundling applications installed in your system. Primary use case is building and bundling applications from source, as you do.

**Comment by IoriBranford** [comment]
Found the issue in LOVE. It sets the desktop file's Exec entry to an absolute path /usr/bin/love. Changing the Exec to just love after building solved the issue. Thank you.
