### ISSUE TITLE
Building on xenial with Qt from ppa cannot find libwebenginewidgets.so.5

### ISSUE THREAD

**Issue by Peterede** [linuxdeploy/linuxdeploy#106]
Calling linuxdeploy:
`./linuxdeploy-x86_64.AppImage  --appimage-extract-and-run --appdir AppDir -e myapp -i default.png -d default.desktop --output appimage`
ERROR: Could not find dependency: libQt5WebEngineWidgets.so.5 
This is located in /opt/qt512/lib/libQt5WebEngineWidgets.so.5 and the app was able to find it when building on the commandline using qmake followed by make.
The paths were set using `bash /opt/qt512/bin/qt512-env.sh`
Possibly linuxdeploy is not using the LD_LIBRARY_PATH path?

**Comment by TheAssassin** [comment]
Please `export QMAKE=path/to/your/qmake` and try again.

**Comment by TheAssassin** [comment]
Oh, you're using those PPAs? That's quite strange then.

linuxdeploy uses `ldd` internally to find out about dependencies of binaries. Can you run `ldd` on your binary please?

Also, if possible, please provide a full log.

**Comment by Peterede** [comment]
In the ldd it is showing:
	libQt5WebEngineWidgets.so.5 => not found
	libQt5PrintSupport.so.5 => not found
	libQt5Svg.so.5 => not found
	libQt5Widgets.so.5 => not found
	libQt5Multimedia.so.5 => not found
	libQt5WebEngineCore.so.5 => not found
	libQt5Quick.so.5 => not found
	libQt5Gui.so.5 => not found
	libQt5WebSockets.so.5 => not found
	libQt5WebChannel.so.5 => not found
	libQt5Qml.so.5 => not found
	libQt5Network.so.5 => not found
	libQt5Xml.so.5 => not found
	libQt5Positioning.so.5 => not found
	libQt5Concurrent.so.5 => not found
	libQt5Core.so.5 => not found
so it seems that qt512-env.sh is not setting the path correctly.  I needed to call `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/qt512/lib
`

**Comment by TheAssassin** [comment]
My `qt510-env.sh` does that... Strange...

Anyway, good it's fixed for you.
