### ISSUE TITLE
Add option to bundle anything

### ISSUE THREAD

**Issue by zaoqi** [linuxdeploy/linuxdeploy#116]

**Comment by TheAssassin** [comment]
Issues without a description will be closed in the future. Please provide a proper description of what you want to have implemented and why you think it's a good idea to invest time.

**Comment by TheAssassin** [comment]
I decided that this tool should not provide such a feature. There are other deployment tools which can do this properly. linuxdeploy is entirely focused around the idea of excluding libraries to reduce bloat, avoid problems interfacing with hardware etc., have security fixes for the most common libraries reach AppImages etc. Alternatives exist which are capable of bundling everything, but they come with many disadvantages, and if you need those features you should probably switch to one of these.
