### ISSUE TITLE
Can't create AppImage without Icon-key in .desktop?

### ISSUE THREAD

**Issue by tastytea** [linuxdeploy/linuxdeploy#117]
Is it possible to create an AppImage of an application that has no icon?

I'm getting this error, after running `linuxdeploy --appdir AppDir --output appimage --verbosity=0`:

```
ERROR: Icon entry missing in desktop file: AppDir/usr/share/applications/de.tastytea.mastorss.desktop 
DEBUG: deployDesktopFileAndIcon returned false
```

The [Desktop Entry Specification](https://specifications.freedesktop.org/desktop-entry-spec/1.0/ar01s05.html) does not require the `Icon` key in its versions 1.0 - 1.4.

**Comment by TheAssassin** [comment]
Interesting find. All I can tell is desktop-file-utils (we use `desktop-file-validate` extensively) complains if you don't have any icon entry in desktop files. For CLI utilities, that's pretty pointless, I know that. The usual workaround is to create a zero-size `something.svg` in your AppDir and use that as "icon".

CC @probonopd, this might require escalation to AppImageKit

**Comment by tastytea** [comment]
Thanks, that works. It seems to be fixed in newer versions of desktop-file-utils. Version 0.24 doesn't care at all about the icon. It doesn't complain if it is absent, has the wrong format or the file doesn't exists.

**Comment by TheAssassin** [comment]
I don't think we bundle a specific version of desktop-file-utils. Mind to open an issue over at https://github.com/AppImage/AppImageKit/issues? We have to decide upstream how to handle this in the future.

**Comment by probonopd** [comment]
Actually we _want_ icons in all AppImages so that the AppImage can be represented with an icon in the system.

**Comment by TheAssassin** [comment]
Nobody needs an icon for CLI tools.

**Comment by probonopd** [comment]
Why not? App Stores, App Centers, AppImageHub, menus, file managers,... can use it...

**Comment by TheAssassin** [comment]
@tastytea I guess you now can see why an icon is required. Closing therefore.
