### ISSUE TITLE
Bundle lib realated files

### ISSUE THREAD

**Issue by azubieta** [linuxdeploy/linuxdeploy#12]
There are cases in which a given lib requires additional data files or other libs (that are not linked) to be bundled like this: https://github.com/probonopd/linuxdeployqt/issues/35

We should consider a way of allowing this.

**Comment by azubieta** [comment]
@probonopd I think you could give us some hints on this as you had to deal whit it previously on linuxdeployqt.

**Comment by TheAssassin** [comment]
I think it makes most sense to build plugins for the purpose, and use the auto discovery feature to make linuxdeploy run the plugins if needed. We should bundle the plugins in linuxdeploy's main AppImage then.

**Comment by probonopd** [comment]
I have not implemented magic sauce for bundling additional data files for libraries yet. Haven't encountered too many of those instances either.
I think what might be a good thing to do is to work on proper `gstreamer` bundling.

**Comment by TheAssassin** [comment]
@probonopd we talked about that today with the KDE guys, and for example Krita and Kdenlive actually could make use of such a plugin for linuxdeploy.

**Comment by TheAssassin** [comment]
Closing here. The strategy for "additional files" will be to use plugins. That keeps things simple and flexible.
