### ISSUE TITLE
patchelf fails to patch openrct2 binaries

### ISSUE THREAD

**Issue by IntelOrca** [linuxdeploy/linuxdeploy#120]
Recently I have noticed our AppImages for OpenRCT2 no longer run correctly. This is because linuxdeploy fails to update the rpath of the OpenRCT2 binaries resulting in missing library errors when running the AppImage.

This is caused by the version of patchelf that is shipped with linuxdeploy. Using patchelf (0.9) from Ubuntu 19.04 seems to patch openrct2 just fine. patchelf (0.8) that comes with linuxdeploy errors.

You can view the logs and download the AppImage here:
https://github.com/OpenRCT2/OpenRCT2/runs/409007891

Here is the output when I run patchelf manually using the one shipped with linuxdeploy:
```
> squashfs-root/usr/bin/patchelf --version
patchelf 0.8
> squashfs-root/usr/bin/patchelf --debug --set-rpath '$ORIGIN/../lib' openrct2
patching ELF file `openrct2'
new rpath is `$ORIGIN/../lib'
rpath is too long, resizing...
DT_NULL index is 43
replacing section `.dynamic' with size 784
replacing section `.dynstr' with size 15230
this is a dynamic library
last page is 0x14bf000
needed space is 16632
warning: working around a Linux kernel bug by creating a hole of 10579968 bytes in ‘openrct2’
maximum file size exceeded
> echo $?
1
```

When I run with the version installed in Ubuntu 19.04:
```
> patchelf --version
patchelf 0.9
> patchelf --debug --set-rpath '$ORIGIN/../lib' openrct2
patching ELF file `openrct2'
Kernel page size is 4096 bytes
new rpath is `$ORIGIN/../lib'
rpath is too long, resizing...
DT_NULL index is 43
replacing section `.dynamic' with size 784
replacing section `.dynstr' with size 15230
this is a dynamic library
last page is 0x14bf000
needed space is 16632
warning: working around a Linux kernel bug by creating a hole of 10579968 bytes in ‘openrct2’
rewriting section `.dynamic' from offset 0x84f6d0 (size 768) to offset 0x14bf268 (size 784)
rewriting section `.dynstr' from offset 0x40d8 (size 15215) to offset 0x14bf578 (size 15230)
rewriting symbol table section 5
rewriting symbol table section 34
> echo $?
0
```

How should I resolve this?
Thanks.

**Comment by TheAssassin** [comment]
> ```
> warning: working around a Linux kernel bug by creating a hole of 10579968 bytes in ‘openrct2’
>```

Haven't seen *that* message in years...

Have you tried running the resulting binary? We have had tons of issues with patchelf `>= 0.9` since it often creates garbled binaries. See https://github.com/linuxdeploy/linuxdeploy/commit/4a7301eba54c4df8eddd75d5b08ebd2a243a4ac1 for more information.

In your case, the newer version might work, but it's not a general solution. You're pretty much the first one for whom 0.8 fails to work.

We might have to investigate doing the "dirty work" ourself at some point.

**Comment by TheAssassin** [comment]
More links:

- https://github.com/NixOS/patchelf/issues/124
- https://github.com/NixOS/patchelf/issues/187

A quick fix will be for you to

**Comment by IntelOrca** [comment]
I see you explicitly checkout 0.8 in your centos dockerfile, could this be bumped up to 0.9 or 0.10?

**Comment by TheAssassin** [comment]
Can you verify `chrpath` works? IIRC we had a reason to use patchelf instead of other tools, but I don't recall them right now. I can set up a test case to check against the Qt libraries tomorrow.

A superior solution would be to patch the bug in `patchelf`. We can maintain a fork in https://github.com/linuxdeploy.

**Comment by TheAssassin** [comment]
By the way, can you please share one of the problematic AppImages for further analysis (and possibly A/B testing), please?

**Comment by IntelOrca** [comment]
https://github.com/OpenRCT2/OpenRCT2/suites/420259229/artifacts/1342067

**Comment by TheAssassin** [comment]
Shipping multiple versions doesn't seem like such a great idea. Given your patchelf you installed works just fine, how about introducing an environment variable that allows you to select a custom patchelf? That'd even allow for building a custom version.

That said, I'd be interested to see if `chrpath` works.

**Comment by IntelOrca** [comment]
`chrpath` can only modify binaries that already specify an rpath, so probably not.
An environment variable to use a different version of patchelf would work.

**Comment by IntelOrca** [comment]
I have resorted to setting the rpath manually now. At least that then means the OpenRCT2 binaries don't grow almost twice the size from patching rpath.
