### ISSUE TITLE
How to avoid the creation of empty directories?

### ISSUE THREAD

**Issue by silvioprog** [linuxdeploy/linuxdeploy#121]
I have the following command line:

```bash
VERSION=$app_version $linuxdeploy --executable bin/$app_name $libs $icons --desktop-file $app_name.desktop --appdir $app_dir --output appimage
```

however, it creates empty unwanted directories like `AppDir/usr/share/icons/hicolor/128x128/apps/`, `AppDir/usr/share/icons/hicolor/256x256/apps/` etc., so I tried to solve it using:

```bash
$linuxdeploy --executable bin/$app_name $libs $icons --desktop-file $app_name.desktop --appdir $app_dir
find $app_dir -type d -empty -delete
$linuxdeploy --appdir $app_dir --output appimage
```
then the empty directories are deleted from `AppDir`, however, they still present in the final generated appimage binary. :-/

So, is there any option to avoid to create those empty directories in the final binary?

TIA for any help!

**Comment by TheAssassin** [comment]
Why don't you like these directories to be created? This is actually a convenience feature, and helps when building an AppDir manually and interactively.

**Comment by silvioprog** [comment]
Some applications doesn't contains all icon sizes, for example, the [Linus' Subsurface](https://subsurface-divelog.org/downloads/Subsurface-4.9.3-x86_64.AppImage) contains only the 256x256 size, so doesn't make much sense to crate the empty directories. 🤔

**Comment by TheAssassin** [comment]
You're optimizing on the wrong end IMO, those directory hardly require any space in the resulting AppImage. I consider this a feature, and use it from time to time. Closing therefore.
