### ISSUE TITLE
Unable to package Qt application

### ISSUE THREAD

**Issue by realnc** [linuxdeploy/linuxdeploy#122]
I'm trying to use linuxdeploy to create a 32-bit appimage of a qt application. I'm normally using linuxdeployqt, but it doesn't support 32-bit so I tried linuxdeploy instead. Problem is, it just doesn't work. If I just create an AppDir, trying to run the application results in:

```
$ ./AppDir/AppRun 
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, minimal, offscreen, vnc, wayland, xcb.

Aborted (core dumped)
```

The readme links to the user guide, but that's a 404 error:

https://docs.appimage.org/packaging-guide/linuxdeploy-user-guide.html

Searching on that site finds this:

https://docs.appimage.org/packaging-guide/from-source/linuxdeploy-user-guide.html

which claims I should use `--plugin qt`. But that doesn't work either:

```
ERROR: Could not find plugin: qt
```

What is the status of linuxdeploy? Is this supposed to even work? The readme claims "consider switching to linuxdeploy", so one would assume it works.

**Comment by realnc** [comment]
OK, turns out I need to manually download the qt plugin. I thought appimage solves the dependency hunt since everything needed can be included in the image.

Sorry for the noise.

**Comment by TheAssassin** [comment]
I see, yeah, that's a point discussed in #32.
As long as you use the 32-bit version, I would expect everything to work.
