### ISSUE TITLE
AppImage uses local folders instead of AppImage folders

### ISSUE THREAD

**Issue by cecilios** [linuxdeploy/linuxdeploy#123]
I 'm attempting to create my first AppImage package using linuxdeploy. The package is built without errors but when I move it to anoter folder and execute it the program fails to locate the needed resources. The app log shows that it is trying to access the correct paths. These paths do no exist in the local system but they exist in the AppImage. So I deduce that AppImage is using local system folders insted of those in the AppImage pack.

**Comment by cecilios** [comment]
I think I've found the problem. My app is trying to load some resources from an absolute path /usr/share/xxxxx. And it seems to be (https://github.com/AppImage/AppImageKit/issues/508) that all paths must be relative to the AppImage executable, provided by getpwd(). Is this correct?

I will modify my program and tests this.

**Comment by cecilios** [comment]
Using the value provided by getcwd() points to current directory in which the app was started, and not to the folder in which the app is installed. So it does not work when the user runs the appimage by mouse click on symlinks.

Using $APPIMAGE seems a better way. See https://github.com/AppImage/AppImageKit/issues/172

In Linux I've not found a simple way of determining the app installation path at run time (see for example https://stackoverflow.com/questions/1023306/finding-current-executables-path-without-proc-self-exe).

**Comment by TheAssassin** [comment]
You can use `$APPIMAGE`, but it'll only work inside the AppImage. You should design applications always in a relocatable manner, and not include any hardcoded paths. The link you discovered provides a suitable way to look up resources relative to your binary.

Please see also https://docs.appimage.org/reference/best-practices.html?highlight=relocatable#binaries-must-not-use-compiled-in-absolute-paths.

**Comment by probonopd** [comment]
Do you want to get the path in which the AppImage is located, or do you want to get the path to your executable inside the AppImage?

**Comment by TheAssassin** [comment]
@probonopd please see the issue in AppImageKit, it's about looking up resources relative to the binary, basically, instead of relying on hardcoded prefixes.

**Comment by probonopd** [comment]
OK, let's continue over there then.
