### ISSUE TITLE
Feature request: Ability to skip setting rpath or stripping specific libraries

### ISSUE THREAD

**Issue by cgapeart** [linuxdeploy/linuxdeploy#127]
I need to include some 3rd party provided libraries in an appimage that have some kind of tamper detection built into them (commercial licensing libraries - out of my control)

To be clear, I recognise this is an unusual situation, and I don't expect a fix:  Just sharing my experience and hoping for suggestions.

Whether I use the -l option, or manually copy the files into the appdir, linuxdeploy processes all the files in the lib directory.

I found the NO_STRIP option, but that has no effect in my case - these libraries don't have debug symbols to begin with.

In the short term, I plan on using linux deploy to prep the appdir, copy the files in manually, but then use appimagetool directly to create the appimage without altering those files.  I realize this may not work at all (because RPATH will cause issues if not changed), but that's the best idea I have so far.

The only other thought I have had is to put them somewhere else in the app image, and update my custom custom apprun script to add that path to the LD search path (LD_LIBRARY_PATH if memory serves).

Comments?

**Comment by cgapeart** [comment]
A successfull workaround:

The libraries in question were manually deployed to the appdir/usr/local/lib, and the custom apprun script adds $appdir/usr/local/lib to LD_LIBRARY_PATH.

I am closing this off - I just wanted to help the next person trying to do something like this.  Feel free to re-open if you think it is something that should be addressed in linuxdeploy.

**Comment by TheAssassin** [comment]
@cgapeart thanks for providing the fix for your solution here. I would also have recommended such an approach.

You should consider making a linuxdeploy plugin for your use case. Plugins can create shell scripts which can export variables etc. and linuxdeploy takes care of launching those on startup.

`DT_RUNPATH` is required by linuxdeploy, as we can _not_ rely on `$LD_LIBRARY_PATH` only for various reasons.
