### ISSUE TITLE
Problems converting from LinuxDeployQt

### ISSUE THREAD

**Issue by Light-Wizzard** [linuxdeploy/linuxdeploy#128]
I am getting a lot of run-time errors like module "QtQuick" is not installed

I am using a modified version of https://github.com/linuxdeploy/QtQuickApp

My project is here: https://github.com/Light-Wizzard/galaxy-calculator

There are links to both AppImages:

LinuxDeployQt
https://github.com/Light-Wizzard/galaxy-calculator/releases/download/continuous/Galaxy-Calculator-travis-x86_64.AppImage

LinuxDeploy
https://github.com/Light-Wizzard/galaxy-calculator/releases/download/continuous/Galaxy-Calculator.AppImage

The script is here https://github.com/Light-Wizzard/galaxy-calculator/blob/master/tools/build-with-qmake.sh

Both files are made from the same compiled version, so I do not get it.

It is not importing the Qt modules.

```
./linuxdeploy-x86_64.AppImage --appdir "AppDir" -e "${BIN_PRO_RES_NAME}" -i "${REPO_ROOT}/resources/${BIN_PRO_RES_NAME}.png" -d "${REPO_ROOT}/resources/${BIN_PRO_RES_NAME}.desktop" --plugin qt --output appimage;
```
I am sure its something I am not doing right, but I am in the right repo this time, and I did read all the docs for this repo, and I did make the switch, and export OUTPUT works as advertised.

This is what confuses me: 

```
This allows for the application to be installed with make install, and for linuxdeployqt to generate an AppImage.
```
Your travis.yml file shows bash `travis/build-with-cmake.sh`  but at the bottom of the page you have:

```
See .travis.yml for how to compile the application on Travis CI, generate an AppImage, and upload it to transfer.sh.
```
It does make both the AppImage, and AppImage.zsync files, they just do not have Qt Quick linked in.

I have made a lot of changes to the file, but it should still work the same, the only thing I do different is I store my Qml in a qml folder, and not src, but I do not see how you link to the Qml folder.

What should these values be set to, my qml is in a qml folder same level as src.

```
# I have never had to use these, I thought they were for qmlscence but changing them did not help.
QML_IMPORT_PATH = $$PWD/qml
QML_IMPORT_PATH = qml
But I am using Qml 2 controls, so wouldn't it be
QML2_IMPORT_PATH = 
# My guess is level this blank I think this is only used by Qt Designer
QML_DESIGNER_IMPORT_PATH =
```

Thanks

**Comment by TheAssassin** [comment]
You are confusing linuxdeployqt and linuxdeploy, it seems. Those tools have *nothing* in common. This is the linuxdeploy issue tracker, so we talk about linuxdeploy only.
Please do not mix linuxdeployqt and linuxdeploy.
Please also provide logs or at least excerpts.

> I am getting a lot of run-time errors like module "QtQuick" is not installed

This does not tell me _anything_, really.

There is absolutely no reason to terminate every script line with `;` by the way.
All your "debug echos" are not needed; bash's `-x` mode already shows you all the values anyway. They just add bloat.

You have overridden the `OUTPUT`, but that's a bad idea the way you've done it. What if you build AppImages for multiple architectures? Better let linuxdeploy-plugin-appimage handle that, unless you make sure your AppImage's architecture shows up the filename. Your update information in fact is also built that way.

The main problem is that you pointed `QML_SOURCES_PATH` to your `src`, but they're actually in your `qml`. After fixing that, linuxdeploy-plugin-qt perfectly realized there is a dependency to QtQuick and deployed a lot of QtQuick files. There have been some errors, though, but it's up to you to find out what's the problem. After all, we just use `qmlimportscanner` internally.

The secondary problem you have is, your QtQuick stuff requires _at least_ version 2.12, which requires _at least_ Qt 5.12, as far as I can tell. I've had to build your application against Qt 5.14 for instance to have a recent-enough Qt. With Qt 5.10, for example, I got:

```sh
> export QT_DEBUG_PLUGINS=1
> ./Galaxy-Calculator*.AppImage
[...]
loaded library "/tmp/galaxy-calculator/squashfs-root/usr/qml/QtQuick.2/libqtquick2plugin.so"
QQmlApplicationEngine failed to load component
qrc:/qml/Main.qml:1 module "QtQuick" version 2.12 is not installed
[...]
```

Which tells me the QtQuick plugin was loaded successfully, but is simply too old.

I'm going to send a PR with the fixed script soon. Please do not write so overly complex scripts full of unnecessary echoes and without a single empty line, they make reading them very hard. I fixed a few of it already.

Next time please also provide a build log, that's really helpful.

**Comment by TheAssassin** [comment]
PR sent: https://github.com/Light-Wizzard/galaxy-calculator/pull/1

**Comment by TheAssassin** [comment]
Closing as resolved.

**Comment by Light-Wizzard** [comment]
I cannot thank you enough.

I started programming in 1969, mostly Mainframe, now just servers, I have a rack, so most of my programming has been in a black box, writing a GUI is new to me, and Travis and AppVeyor are new, and I am not that good at Github, even though I have been using it for a long time, I have memory issues, the Military calls it TBI, Traumatic Brain Injury, that is what happens when something hits you in the head so fast and so hard, that it rips the skin back off your skull, and pulled all the ligaments in my neck, not to mention I almost bleed out,  I was Medically Retired, and have to deal with this and the Cancer I got from Depleted Uranium, so I use Cannabis because it really does treat Cancer, not cure it, that is a myth, I stop using it, and it comes back with a vengeance. Sorry about the long Dialog, I do not get out much as of late. 

I was born in Corona, so I am immune to the Virus, actually, I have Lymphoma, it attacks my own body, I never get sick that easy, due to colds and flus anyway, having to have organs and skin removed, I have bigger things to worry about, other than catching the Corona Flu.

I am writing an Article in my Wiki on how to do this, so others might find it and learn.

I think I found as many mistakes as possible, and I got so mixed up with LinuxDeployQt, and it works fine, but as you know, having the version number in your name is not nice, but your right, the Arch should be there.

I use spellcheck, and it will not pass unless I follow all its rules, when I was in the Miltary, or working for the Government after I was retired, we had to use a tool like it, so I always try to fix all the complaints.

I have some issues to resolve to get the Qt Installer Framework to work right, I could not find any good examples, and Installers of Linux is weird, but I like it and will make one for Max as well.

I want to make these scripts agnostic, so others can use them without having to customize them, but I have to get them to work, before I really write about how to do it, instead of how not to.

I use echos so I do not have to set -x, so I have less to look at, and only use -x when I really am lost, which is why it was on. If this was not open source, I would remove all the comments and echos, and minimize it, then the ";" at the end makes more sense.

I have bash files with more than 100,000 lines when sourced together, more like I wrote programs using it because it was all we had in common, a terminal, I normally ssh into my dev machines, so I do not have to sit in front of a rack all day.

I even converted this project form a bash program that is included, it creates the web page that displays the results, mainly so you can save different Galaxy configurations.

When I am done I will create a Demo Project, much like you did, showing how to make LinuxDeploy apps, and I still have not figured out how to use zsync files, and use the AppImageUpdate, so I have a long way to go, and I still need to make the Mac installer, and then Android.

Thanks again
