### ISSUE TITLE
Question about UPDATE_INFORMATION

### ISSUE THREAD

**Issue by Light-Wizzard** [linuxdeploy/linuxdeploy#129]
Currently, I am using the below, the zsync file exists, but its not working, using the format:

```
https://github.com/${GITHUB_USERNAME}/${GITHUB_PROJECT}/releases/download/continuous/AppName-x86_64.AppImage.zsync
```

I get an error No .zsync file specified.

My setting

```
export UPDATE_INFORMATION="gh-releases-zsync|${GITHUB_USERNAME}|${GITHUB_PROJECT}|continuous|${ARTIFACT_ZSYNC}"
```

Looking at the documentation and examples I got confused:

```
https://docs.appimage.org/packaging-guide/from-source/linuxdeploy-user-guide.html
export UPDATE_INFORMATION="gh-releases-zsync|neovim|neovim|$TAG|nvim.appimage.zsync"
or
export UPDATE_INFORMATION="gh-releases-zsync|AppImage|appimaged|continuous|appimaged*$ARCH*.AppImage.zsync"
```

I want to try the AppImageUpdate feature, but I cannot get this to work with zsync.

Here is an example of another failure

```
zsync https://github.com/AppImage/appimaged/releases/download/continuous/appimaged-i386.AppImage.zsync
```

Here is an example of one that works

```
zsync http://releases.ubuntu.com/19.04/ubuntu-19.04-desktop-amd64.iso.zsync
```

Thanks

**Comment by TheAssassin** [comment]
You are using `zsync` version 1, which cannot work with HTTPS links. Therefore, there's a fork called `zsync2`, which _can_ work with those links. See https://github.com/AppImage/zsync2.

Your update information looks correct. Please try updating your AppImage with https://github.com/AppImage/AppImageUpdate.

All these questions belong to https://github.com/AppImage/AppImageKit by the way.

**Comment by Light-Wizzard** [comment]
Thanks you have been a big help, I am not on my game with this yet.
