### ISSUE TITLE
Fail to make appdir of pidgin: ERROR: Could not find dependency: libgnt.so.0 

### ISSUE THREAD

**Issue by imtiazShakil** [linuxdeploy/linuxdeploy#130]
I'm trying to make AppImage of pidgin but failing to make a working appdir. 
I've done the following steps:

1. Downloaded latest stable pidgin from [bitbucket](https://bitbucket.org/pidgin/main/downloads/pidgin-2.13.0.tar.gz)
2. installed all the development headers for pidgin:
 `sudo apt-get build-dep pidgin`
3. ran `configure` script inside the project: `./configure --prefix=/usr`
4. ran make command: `make`
5. ran make install command: `make install DESTDIR=/home/user/myappdir`
6. ran linuxdeploy: `linuxdeploy-x86_64.AppImage --appdir myappdir`

I'm getting the following error message:
```-- Deploying dependencies for existing files in AppDir -- 
Deploying dependencies for ELF file ./myappdir/usr/bin/finch 
ERROR: Could not find dependency: libgnt.so.0 
ERROR: Failed to deploy dependencies for existing files 
```

I'm running lubuntu 18.04 lts

After running `make install DESTDIR` I've all the files specified by AppImage e.g.
```
/usr
/usr/bin/
/usr/include/
/usr/lib/
/usr/share/
```
The library `libgnt.so.0` also exist in `./usr/lib` directory but still the error says it's missing. 

I checked AppImage Documentation but don't know how to approach with these errors. Any help would be appreciated. Thanks.

**Comment by TheAssassin** [comment]
linuxdeploy doesn't "see" dependencies "installed" into an AppDir with `make install DESTDIR=...`, unless those already have a DT_RUNPATH set.

Therefore, can you please `export LD_LIBRARY_PATH=/home/user/myappdir/usr/lib` and check if that fixes the issue?

If that fixes the issue, then we'll patch linuxdeploy to do exactly that before trying to look up dependencies. You're not the first one to hit this problem. It's not our fault, it's the incomplete build system of Pidgin in this case. However, we can rather safely work around it, so there's no reason not to do so.

**Comment by imtiazShakil** [comment]
Yes, you're correct.

I didn't had `LD_LIBRARY_PATH` set, but when I exported it linuxdeploy worked without any issues.

**Comment by imtiazShakil** [comment]
But now I'm having a different problem after I create the appimage.

when I run the appimage, I get:
```
./Pidgin_Internet_Messenger-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_PidginorugpS/usr/bin/../lib/libgstreamer-1.0.so.0)
./Pidgin_Internet_Messenger-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_PidginorugpS/usr/bin/../lib/libgtk-x11-2.0.so.0)
./Pidgin_Internet_Messenger-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_PidginorugpS/usr/bin/../lib/libcairo.so.2)
./Pidgin_Internet_Messenger-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_PidginorugpS/usr/bin/../lib/libpurple.so.0)
./Pidgin_Internet_Messenger-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_PidginorugpS/usr/bin/../lib/libpixman-1.so.0)
./Pidgin_Internet_Messenger-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_PidginorugpS/usr/bin/../lib/libpng16.so.16)
./Pidgin_Internet_Messenger-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_PidginorugpS/usr/bin/../lib/libxml2.so.2)
./Pidgin_Internet_Messenger-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_PidginorugpS/usr/bin/../lib/libxml2.so.2)
./Pidgin_Internet_Messenger-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_PidginorugpS/usr/bin/../lib/libgstvideo-1.0.so.0)
./Pidgin_Internet_Messenger-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_PidginorugpS/usr/bin/../lib/libicuuc.so.63)
```

How I can ship these missing library files so that appimage can find them? 
Thanks for your help

**Comment by TheAssassin** [comment]
You must not bundle libc for various reasons. There is a reason linuxdeploy has not bundled it for you. 

Please see https://docs.appimage.org/introduction/concepts.html#build-on-old-systems-run-on-newer-systems. You need to build your AppImage on some old distribution to make it work. The oldest still-supported Ubuntu LTS for example (as of 2020 this is xenial) would work.

**Comment by imtiazShakil** [comment]
Thanks for the advice, I'll try with an older ubuntu lts version.

**Comment by azubieta** [comment]
> Thanks for the advice, I'll try with an older ubuntu lts version inshaAllah.

If you struggle too much to get your software built on older ubuntu lts you can try https://github.com/appimagecrafters/appimage-builder It allows creating AppImages on newer system while the backward compatibility is keep

**Comment by TheAssassin** [comment]
Closing as resolved.
