### ISSUE TITLE
Manage a temporary directory for AppRun

### ISSUE THREAD

**Issue by X0rg** [linuxdeploy/linuxdeploy#133]
In some cases, AppRun hooks require to write files to file system (like cache files).

It would be great if linuxdeploy can create a temporary directory, set up an environment variable that can be used by hooks, and clean up this directory when AppImage exits.

More information: linuxdeploy/linuxdeploy-plugin-gtk#1

**Comment by TheAssassin** [comment]
We have to replace the `exec` call with some subprocess handling in the wrapper script linuxdeploy creates automatically for that to work. Then, after the payload application has terminated, the bash script is in charge again, and (potential) clean up stuff can be run as expected.

**Comment by X0rg** [comment]
I'm still thinking about this... Do we really need the `exec` builtin command? Without it, it will allow the wrapper script to cleanup stuff after payload application has terminated.

**Comment by X0rg** [comment]
Let's close this issue (see my comment [here](https://github.com/linuxdeploy/linuxdeploy/pull/164#issuecomment-1047148808)).
