### ISSUE TITLE
Skipping deployment of blacklisted library

### ISSUE THREAD

**Issue by ZaxonXP** [linuxdeploy/linuxdeploy#134]
I was trying to package the `newsboat` app on a new system to be deployed on old system (I described it [here](https://github.com/AppImage/AppImageKit/issues/1058#issue-650397457)). However some of the libraries on the old system are in old version and not compatible with the packaged app. 

It was pointed to me that the AppImage does not package all as there is exception list (described here in section: ["Build on old systems, run on newer systems"](https://docs.appimage.org/introduction/concepts.html#build-on-old-systems-run-on-newer-systems)).

However the section before (["Do not depend on system-provided resources"](https://docs.appimage.org/introduction/concepts.html#do-not-depend-on-system-provided-resources)) would suggest that all needed resources should be packaged. How can I force to add these skipped libraries to have a complete image with a proper version libraries? Is this possible? Where is the list of exception to modify?

Regards,
Piotr

**Comment by TheAssassin** [comment]
What you want is to bundle everything. This is not supported in linuxdeploy. Bundling every library requires bundling *everything* including libc, the glibc loader and a few more things, with some runtime code that guessifies whether to use those bundled data at all, etc. It's a lot of hassle.

linuxdeploy is (as of yet) tailored to the best practices established in the past years. I could imagine supporting this use case by implementing a plugin (as suggested in #5), but it's not a priority.

You could still build your own libraries, e.g., with up to date versions.
