### ISSUE TITLE
Possibility to deploy dependencies for libraries/executables in AppDir without changing their location

### ISSUE THREAD

**Issue by TheAssassin** [linuxdeploy/linuxdeploy#136]
It should be possible for users to have linuxdeploy deploy the dependencies of some ELF files only, without changing their location. We should add another parameter next to `-e` and `-l` for this purpose.

CC @freakboy3742

**Comment by shoogle** [comment]
What does it mean to deploy something without changing the location (of the thing or of the dependency?)?

**Comment by freakboy3742** [comment]
As requested on IRC; here's my use case:

I have an AppImage which is a wrapper around a Python project. The AppImage contains both a Python interpreter, and a collection of dynamic modules (distributed as `.so` files). 

The .so files are distributed in a directory structure that is understood by the Python interpreter, not literally in the `/usr/lib` folder. The location is significant to Python, so they can't be moved to /usr/lib (at least, not easily).

Running linuxdeploy to build the app pulls in all the dependencies of the libs in `/usr/lib`; but *not* for any of the dynamic modules.

As a result, when the app is built on Ubuntu 16.04, it runs fine on Ubuntu 16.04; but if you run the app on Ubuntu 20.04, it fails when you try to `import ctypes`, failing with the error:
```
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
```

Pulling apart the AppImage, running `ldd` on the binary module for ctypes (`<appImage>/usr/lib/python3.7/lib-dynload/_ctypes.cpython-37m-x86_64-linux-gnu.so`) has a dependency on the *system* version of `/usr/lib/x86_64-linux-gnu/libffi.so.6`.

(Ironically - libffi.so.6 *is* in in the AppImage for other reasons; but _ctypes.so doesn't link against it).

As a linuxdeploy user, I would like to be able to (in order of preference):

1. have *any* `.so` file in the AppImage be relocatable without needing to specifically list them; or
2. be able to specify folders in addition to /usr/lib that contain libraries that need to be relocatable; or
3. provide a command line list of individual .so files that need to be relocatable.

From the sound of @TheAssassin's description, (2) or (3) is more likely to be actually implemented.

**Comment by TheAssassin** [comment]
Example:

```
AppDir/
  usr/
    bin/
      myapp
    lib/
      myapp/
        mylib.so
```

Imagine `mlib.so` to be a plugin that is loaded dynamically with `ldopen`. linuxdeploy cannot directly see the dependency (see #77), so we could give the user the option to specify such binaries themselves. All linuxdeploy has to do is deploy their dependencies and set the correct rpath. It's similar to what is done in the Qt plugin, and supported by the `AppDir` class already. We just need some frontend integration I presume.

Another advantage of having support for that is plugins can make use of it. Plugins nowadays get passed a `$LINUXDEPLOY` environment variable with its path, so they could make use of this directly, too.

**Comment by ju6ge** [comment]
I am running into this Problem as well. In my case i have a qt application which is extendable via plugins. The plugins are shared libraries that get installed into a directory that is only meaningful to the application and they may need additional dependencies. 

I think an option to specify a directory or list of libraries that are already in the appimage thanks to ```make install DESTDIR=<AppDir>``` and need to be relocatable would be the best solution to enable this use case.
