### ISSUE TITLE
Must provide icon and desktop?

### ISSUE THREAD

**Issue by c02y** [linuxdeploy/linuxdeploy#138]
I need to create appimage of program only running inside terminal, so the program doesn't have icon and desktop file.

But `linuxdeploy ... --output appimage` failed because of lack of desktop or icon. 

How can I create appimage without providing icon and desktop？

If linuxdeploy doesn't provide this feature, is this feature in the todo list?

**Comment by TheAssassin** [comment]
Those files are required by the [AppDir specification](https://docs.appimage.org/reference/appdir.html#general-description). You need to provide those also for CLI tools. But writing a desktop entry is not hard, and the icon will also be shown when looking at your AppImage in a file browser.
If you don't have an icon, you can create an empty file with an `.svg` extension.

**Comment by TheAssassin** [comment]
Closing as resolved. Please refer to https://github.com/AppImage/AppImageKit for further questions.
