### ISSUE TITLE
Subprocess output prefixing causes plugins to hang

### ISSUE THREAD

**Issue by TheAssassin** [linuxdeploy/linuxdeploy#14]
I guess the issue is somewhere in https://github.com/linuxdeploy/linuxdeploy/blob/master/include/linuxdeploy/plugin/base_impl.h#L150. We should make sure that plugins like Qt don't hang due to this. See https://github.com/linuxdeploy/linuxdeploy-plugin-qt/issues/12.

**Comment by vaibhavpandeyvpz** [comment]
Okay, I see it here. Subscribed.

**Comment by azubieta** [comment]
It seems that this issue is not totally solved, will reopen for more investigation.

**Comment by milohr** [comment]
This issue affects the creation of AppImages for Maui Apps, for example, for Index (file manager):
I'm on KDE Neon, and I'm using this script to create the AppImage:
https://gist.github.com/azubieta/916d1993c4c8ef06ec1a05789b89a3a7

The process hangs at this step:

-- Deploying module: qml -- 
QML imports search path: /usr/lib/x86_64-linux-gnu/qt5/qml /home/camilo/Coding/appimages/usr/lib/x86_64-linux-gnu/qml /usr/lib/x86_64-linux-gnu/qt5/qml
QML sources search path: /home/camilo/Coding/appimages/index-fm/build/../src/ AppDir
Calling: /usr/lib/qt5/bin/qmlimportscanner -rootPath /home/camilo/Coding/appimages/index-fm/build/../src/ -rootPath AppDir -importPath /usr/lib/x86_64-linux-gnu/qt5/qml -importPath /home/camilo/Coding/appimages/usr/lib/x86_64-linux-gnu/qml -importPath /usr/lib/x86_64-linux-gnu/qt5/qml

**Comment by TheAssassin** [comment]
I've seen `qmlimportscanner` hanging, too, but every time it was the process that really hung, and linuxdeploy didn't seem to misbehave. Try calling that program on your computer please.

Anyway, this issue is really old and from the beginning days of linuxdeploy. Your issue is likely unrelated, as this was about prefixing the output of processes. Yours is about communication with an external subprocess, which is something entirely different. Also, it belongs to the linuxdeploy-plugin-qt project. Please open an issue over there.
