### ISSUE TITLE
Sets permissions of top-level directory to 0600, should be 0755

### ISSUE THREAD

**Issue by probonopd** [linuxdeploy/linuxdeploy#140]
According to https://github.com/jeanslack/Videomass/issues/4#issuecomment-667986905,

> using linuxdeploy-x86_64.AppImage to make the videomass AppImage package causes the permissions to change to 0600 during the extraction with the ./Videomass-3.0.0-1_x86_64.AppImage --appimage-extract command

Permissions should be 0755 for that directory, not 0600.

This has been [verified](https://github.com/jeanslack/Videomass/issues/4#issuecomment-667998619) to still be an issue in the latest continuous build as of today.

**Comment by TheAssassin** [comment]
Need a link to the original AppImage. Also, please don't report on behalf of other people, just send them here. Asking questions through a gateway is pointless.

**Comment by probonopd** [comment]
Original AppImage:
https://sourceforge.net/projects/videomass2/files/V3.0.0/Linux/Videomass-3.0.0-x86_64.AppImage/download

I am sure @jenslack is willing to answer questions.

**Comment by jeanslack** [comment]
Hello, maybe now it's better to use the AppImage with the correct permissions:
https://sourceforge.net/projects/videomass2/files/V3.0.0/Linux/Videomass-3.0.0-1_x86_64.AppImage/download

**Comment by jeanslack** [comment]
Today I tested the latest continuous build of linuxdeploy to make a new AppImage release, but it failed to complete it successfully and I had to abort it with `ctrl+c` as the process never finished (but this is another linuxdeploy issue). 
However, the permissions now look fixed to 0755.

Thanks for your work with AppImage.

**Comment by TheAssassin** [comment]
See #143.

**Comment by TheAssassin** [comment]
linuxdeploy doesn't alter permissions anyway as far as I can tell. I guess it might've been some old version of e.g., the AppImage plugin, causing these problems. Anyway, closing as resolved.
