### ISSUE TITLE
i386 Build Disappeared

### ISSUE THREAD

**Issue by CalcProgrammer1** [linuxdeploy/linuxdeploy#141]
Looks like your CI job failed and thus the i386 release disappeared from GitHub.  I use this in my GitLab CI instance and builds have been failing today.

Edit:  My failing build: https://gitlab.com/CalcProgrammer1/OpenRGB/-/jobs/672670129

**Comment by TheAssassin** [comment]
Working on it. See https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/issues/15 for more information. The CentOS 6 setup just doesn't work any more.

**Comment by TheAssassin** [comment]
In the meantime, you can use the last successful build, https://artifacts.assassinate-you.net/artifactory/linuxdeploy/travis-456/linuxdeploy-i386.AppImage.

**Comment by TheAssassin** [comment]
Building static binaries now. Still have some problems with that, see #142.
