### ISSUE TITLE
Deployment missing between plugin execution and code signing

### ISSUE THREAD

**Issue by julonexus** [linuxdeploy/linuxdeploy#144]
Since the last build of continuous build, I got this output :

```
-- Running input plugin: qt -- 
Running process: /builds/BC/public/linphone-desktop/build/WORK/Packages/AppImageDir/AppBin/linuxdeploy-plugin-qt-x86_64.AppImage --appdir WORK/Packages/AppImageDir/AppDir
-- Code Signing of AppImage
```

There is no more deploying. 6 days ago, between these 2 steps, I get :
```

-- Running input plugin: qt -- 
... blabla Qt plugin stuff
-- Deploying icons -- 
....
-- Deploying desktop files -- 
....
-- Copying files into AppDir -- 
....
-- Deploying files into AppDir root directory -- 
....
-- Code Signing of AppImage
```

That lead to not having all files, and AppImage cannot be created

**Comment by julonexus** [comment]
In fact, Copying files into AppDir was a duplicate (it copied the same file at the same location)
But in the new build, there is no more -- Deploying icons --, -- Deploying desktop files -- and 
-- Deploying files into AppDir root directory --

**Comment by TheAssassin** [comment]
Whatever `Code Signing of AppImage` is, it is not coming from linuxdeploy. Your report likely lacks information. Can you please provide a link to your build script?

**Comment by julonexus** [comment]
I'm using 3 AppImages for the creation and the only change has been about linuxdeploy-x86_64.AppImage.
--2020-08-11 10:10:59--  https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
--2020-08-11 10:11:00--  https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
(This one didn't change since 2020-07-07)
--2020-08-11 10:11:02--  https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
(this one didn't change since 2020-07-09)

The issue comes from :
Segmentation fault      (core dumped) ./${WORK_DIR}/AppBin/linuxdeploy-x86_64.AppImage --appdir=${WORK_DIR}/AppDir -e ${WORK_DIR}/AppDir/usr/bin/linphone --desktop-file=${WORK_DIR}/AppDir/usr/share/applications/linphone.desktop -i ${WORK_DIR}/AppDir/usr/share/icons/hicolor/scalable/apps/linphone.svg --plugin qt

If you still want the script, it can be found [here](https://gitlab.linphone.org/BC/public/linphone-desktop/blob/master/linphone-app/tools/create_appimage.sh)

**Comment by TheAssassin** [comment]
I cannot see a segfault message in your first post. I presume you're also a victim of #143.

**Comment by julonexus** [comment]
Yes, I didn't do the correlation because the error shown after the code signing message. I guess you're right about this issue
