### ISSUE TITLE
Cannot include static-built binary inside AppImage

### ISSUE THREAD

**Issue by JokerQyou** [linuxdeploy/linuxdeploy#147]
I was writing an GUI software which needs to call an external binary tool, so it seems reasonable to include multiple binaries inside a single AppImage bundle. But the other binary tool was a static binary, and `linuxdeploy` is failing to inspect it. I have `linuxdeploy version 1-alpha (git commit ID e9bbbc8), Travis build 479 built on 2020-08-31 06:43:49 UTC`, downloaded from the release page.

The command I ran was `./linuxdeploy.AppImage --executable=cloak --appdia AppDir --desktop-file Cloak.desktop --icon-file Cloak.svg --output appimage`

The log output was:

```
...
terminate called after throwing an instance of 'std::runtime_error'
  what(): Failed to run ldd: exited with code 1
Aborted (core dumped)
```

The static binary I was trying to include was a statically linked Golang program, you can download it [here](https://github.com/rfjakob/gocryptfs/releases/download/v1.8.0/gocryptfs_v1.8.0_linux-static_amd64.tar.gz).

**Comment by TheAssassin** [comment]
Please try the latest version.

**Comment by JokerQyou** [comment]
> Please try the latest version.

The latest version behaves the same. Version is now `linuxdeploy version 1-alpha (git commit ID e4fff0a) Travis build 483 built on 2020-09-22 11:49:39 UTC`.

**Comment by JokerQyou** [comment]
I found the related logic in linuxdeploy [here](https://github.com/linuxdeploy/linuxdeploy/blob/4d999ef5c61907380497d3db18e1a3a594bab5ae/src/core/elf.cpp#L165), but you are comparing `stdout` string, and `ldd` is actually printing `not a dynamic executable` into `stderr`.

**Comment by TheAssassin** [comment]
> linuxdeploy is not wrong when it says failed to run ldd: exited with code 1, because that's just how ldd works with statically-linked binaries, it prints not a dynamic executable and exit with 1:

Weird. linuxdeploy is also built as a static binary in its own CI setup, but there the tool doesn't crash, it just prints a warning and continues: https://travis-ci.org/github/linuxdeploy/linuxdeploy/jobs/729283353#L8389-L8390

It looks like your `ldd` behaves weirdly. You have not mentioned on what distro you run your deployment...

**Comment by JokerQyou** [comment]
I'm running `Linux Mint 20 Ulyana`, ldd version is `ldd (Ubuntu GLIBC 2.31-0ubuntu9) 2.31`.

**Comment by TheAssassin** [comment]
The question is why the exception in https://github.com/linuxdeploy/linuxdeploy/blob/4d999ef5c61907380497d3db18e1a3a594bab5ae/src/core/elf.cpp#L164-L171 doesn't work...

**Comment by TheAssassin** [comment]
Please provide a complete debug log (`-v0`).

**Comment by JokerQyou** [comment]
> The question is why the exception in
> 
> https://github.com/linuxdeploy/linuxdeploy/blob/4d999ef5c61907380497d3db18e1a3a594bab5ae/src/core/elf.cpp#L164-L171
> doesn't work...

Like [I said](https://github.com/linuxdeploy/linuxdeploy/issues/147#issuecomment-696800123), I suspect it does not work because `ldd` prints the error message into `stderr` not `stdout`. I'll provide a complete debug log soon.

**Comment by JokerQyou** [comment]
Here is the debug log: [test.log](https://github.com/linuxdeploy/linuxdeploy/files/5265013/test.log).

To verify my previous suspecion:

```bash
$ ldd gocryptfs
	not a dynamic executable
$ echo $?
1
$ ldd gocryptfs 1>/dev/null
	not a dynamic executable
$ ldd gocryptfs 2>/dev/null
$
```

So `ldd` is indeed printing error message to `stderr` instead of `stdout`.

**Comment by TheAssassin** [comment]
I see. Must've missed that bit. Doesn't make a lot of sense to me to change this... Will check out your PR ASAP.
