### ISSUE TITLE
Simple bash based plugins

### ISSUE THREAD

**Issue by mnesarco** [linuxdeploy/linuxdeploy#159]
Hi Friends,
As plugins are just executables, it is easy to create very simple plugins as bash scripts.

I have created a simple plugin to configure the XDG icon of the AppImage, so at least on XDG supported platforms, the AppImage have an icon without installing appimaged.

The script is very simple but demoes how to write simple plugins, I left the code here because it can be useful for someone.

https://gist.github.com/mnesarco/6e5712ef836bfdd330178ff2bc9be54c

Cheers,
Frank.

**Comment by TheAssassin** [comment]
We already have a bunch of shell script plugins maintained by linuxdeploy:

- https://github.com/linuxdeploy/linuxdeploy-plugin-gtk
- https://github.com/linuxdeploy/linuxdeploy-plugin-conda
- https://github.com/linuxdeploy/linuxdeploy-plugin-gstreamer
- https://github.com/linuxdeploy/linuxdeploy-plugin-checkrt

People seem to like this design decision to interface plugins as child processes, configuring them via parameters and environment variables.

**Comment by mnesarco** [comment]
@TheAssassin yes I know there are some plugins, I was just demoing how to develop very simple custom plugins for specific needs. Thanks to the plugins interface based on just environment variables, it is possible to develop plugins in any languaje.

**Comment by TheAssassin** [comment]
Yup, that was the idea initially. It grants a lot of freedom to plugin creators. The interface is even pretty basic now, there's tons of ideas how to extend and improve it, but I hardly ever get to working on most projects. I would like to support, e.g., different stages where plugins could hook into. See #68.

Closing as resolved. I think you should probably put this on the wiki so it will be seen.
