### ISSUE TITLE
Repo request: linuxdeploy-plugin-ncurses

### ISSUE THREAD

**Issue by X0rg** [linuxdeploy/linuxdeploy#161]
Hello,

I would like to propose a new plugin, for ncurses-based applications.
In my experience, terminfo must be copied into AppDir to avoid incompatibilities.

I have a Gist for that: https://gist.github.com/X0rg/fc7f1fb9edc3654d67a22c7ddb7b81be

**Comment by TheAssassin** [comment]
Sure, let me create a repo and invite you there.

**Comment by TheAssassin** [comment]
https://github.com/linuxdeploy/linuxdeploy-plugin-ncurses/

**Comment by X0rg** [comment]
Thanks @TheAssassin!

**Comment by TheAssassin** [comment]
I have to thank you for your commitment to linuxdeploy. It's hard to find contributors.
