### ISSUE TITLE
for some reason linuxdeploy really, wants access to the /root/.gem files

### ISSUE THREAD

**Issue by SolarAquarion** [linuxdeploy/linuxdeploy#162]
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::status: Permission denied: "/root/.gem/ruby/2.3.0/bin

**Comment by TheAssassin** [comment]
You're not providing the bare minimum of information. How shall anyone work on this? Why do maintainers always have to ask the same questions, over and over again?

Read https://www.chiark.greenend.org.uk/~sgtatham/bugs.html and try again.

At least the version of linuxdeploy, your OS, name and repo link of your app, what you were trying to accomplish, a full(!) log are required.

**Comment by SolarAquarion** [comment]
continuous-1, Arch Linux.

`linuxdeploy version 1-alpha (git commit ID 9fb2ac3), <local dev build> built on 2021-01-18 14:16:48 UTC
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::status: Permission denied: "/root/.gem/ruby/2.3.0/bin"
[1]    2819011 abort (core dumped)  ./build/bin/linuxdeploy
`

is linuxdeploy need root access for example to /dev/fuse or whatever?

**Comment by TheAssassin** [comment]
Still waiting for the logs. Have you resolved the issue already? If so, please share your solution.
