### ISSUE TITLE
AppImage changed size while reading filesystem

### ISSUE THREAD

**Issue by KitsuneRal** [linuxdeploy/linuxdeploy#163]
I fail to see what's at a loss but when trying to use linuxdeploy (with different directories) in GitHub Actions it consistently times out with neverending "AppImage changed size while reading filesystem" messages instead of successful squashfs creation. I made sure I'm not trying to write to the directory I read from, changed the layout a couple more times; but the issue persists. The project is here: https://github.com/quotient-im/Quaternion/actions - do I miss something obvious or is GitHub playing tricks with the filesystem behind the scene?

**Comment by KitsuneRal** [comment]
I still have no idea what was up but switching `DESTDIR` to a temporary directory helped. Closing this.

**Comment by TheAssassin** [comment]
Seems more like a GitHub actions weirdness, looking at https://github.com/quotient-im/Quaternion/commit/2e0780dce20f06814cfadd0f54c968f94713a784. Glad it works now.
