### ISSUE TITLE
sudo command responds with "Killed"

### ISSUE THREAD

**Issue by UDPSendToFailed** [linuxdeploy/linuxdeploy#165]
I have tried both VNC and SSH methods, same problem.

![image](https://user-images.githubusercontent.com/16057404/106633861-7e59d300-657f-11eb-8816-b51961f31378.png)

Samsung SM-T590
Resurrection Remix 8.6.4 (Android 10)
Magisk 21.1

**Comment by TheAssassin** [comment]
This is not the project you are looking for. You probably want to ask the "other" linuxdeploy.

**Comment by UDPSendToFailed** [comment]
Oh, sorry man, my bad. :D
