### ISSUE TITLE
Update patchelf to 0.10+

### ISSUE THREAD

**Issue by qurious-pixel** [linuxdeploy/linuxdeploy#167]
Request to update patchelf (currently using version 0.8) to something more modern (version 0.12).
to fix the issue found here:
https://github.com/NixOS/patchelf/issues/92

Currently replacing patchelf in my CI.

**Comment by TheAssassin** [comment]
`patchelf` of versions newer than 0.8 have shown to regularly break the ELF binaries in combination with the other tools we use to optimize the AppImage size, e.g., `strip`. I remember that the issue persisted in 0.10, but I might be wrong.

How certain are you that `0.12` no longer breaks the ELF binaries? Can you share your project so we can have a look?

**Comment by qurious-pixel** [comment]
I build patchelf 0.12 in my Docker image, then replace at runtime. If I use the default "0.08" it fails to package the image, as the binary is too big.

[Docker Image](https://github.com/qurious-pixel/pcsx2/blob/5eea3e436e9c2b6ca0df579c9ac3dbb2dda73461/.github/workflows/scripts/docker/Dockerfile_x64#L71-L76)

[Project Repo](https://github.com/qurious-pixel/pcsx2/tree/app-test)
