### ISSUE TITLE
An icon file is picked at random when there are a few available

### ISSUE THREAD

**Issue by KitsuneRal** [linuxdeploy/linuxdeploy#168]
The issue can be observed when looking at https://github.com/quotient-im/Quaternion/runs/2156723257?check_suite_focus=true#step:17:7387:
```
-- Deploying files into AppDir root directory -- 
WARNING: No desktop file specified, using first desktop file found: /home/runner/work/Quaternion/Quaternion/install/usr/share/applications/com.github.quaternion.desktop 
Deploying files to AppDir root using desktop file: /home/runner/work/Quaternion/Quaternion/install/usr/share/applications/com.github.quaternion.desktop 
Deploying desktop file to AppDir root: /home/runner/work/Quaternion/Quaternion/install/usr/share/applications/com.github.quaternion.desktop 
Creating symlink for file /home/runner/work/Quaternion/Quaternion/install/usr/share/applications/com.github.quaternion.desktop in/as /home/runner/work/Quaternion/Quaternion/install 
Deploying icon to AppDir root: /home/runner/work/Quaternion/Quaternion/install/usr/share/icons/hicolor/16x16/apps/quaternion.png 
Creating symlink for file /home/runner/work/Quaternion/Quaternion/install/usr/share/icons/hicolor/16x16/apps/quaternion.png in/as /home/runner/work/Quaternion/Quaternion/install 
Deploying AppRun symlink for executable in AppDir root: /home/runner/work/Quaternion/Quaternion/install/usr/bin/quaternion 
Creating symlink for file /home/runner/work/Quaternion/Quaternion/install/usr/bin/quaternion in/as /home/runner/work/Quaternion/Quaternion/install/AppRun 
```
and, a few days later with no changes to the relevant code, https://github.com/quotient-im/Quaternion/runs/2196823924?check_suite_focus=true#step:17:7414:
```
-- Deploying files into AppDir root directory -- 
WARNING: No desktop file specified, using first desktop file found: /home/runner/work/Quaternion/Quaternion/install/usr/share/applications/com.github.quaternion.desktop 
Deploying files to AppDir root using desktop file: /home/runner/work/Quaternion/Quaternion/install/usr/share/applications/com.github.quaternion.desktop 
Deploying desktop file to AppDir root: /home/runner/work/Quaternion/Quaternion/install/usr/share/applications/com.github.quaternion.desktop 
Creating symlink for file /home/runner/work/Quaternion/Quaternion/install/usr/share/applications/com.github.quaternion.desktop in/as /home/runner/work/Quaternion/Quaternion/install 
Deploying icon to AppDir root: /home/runner/work/Quaternion/Quaternion/install/usr/share/icons/hicolor/scalable/apps/quaternion.svgz 
Creating symlink for file /home/runner/work/Quaternion/Quaternion/install/usr/share/icons/hicolor/scalable/apps/quaternion.svgz in/as /home/runner/work/Quaternion/Quaternion/install 
Deploying AppRun symlink for executable in AppDir root: /home/runner/work/Quaternion/Quaternion/install/usr/bin/quaternion 
Creating symlink for file /home/runner/work/Quaternion/Quaternion/install/usr/bin/quaternion in/as /home/runner/work/Quaternion/Quaternion/install/AppRun 
```
(the latter further causing a failure because svgz files are not supposed to be used for desktop entries)

The problem is that [this code](https://github.com/linuxdeploy/linuxdeploy/blob/b6a1ba290e2e8fe232eac30e0af52e51c49b1131/src/core/appdir_root_setup.cpp#L54) does not provide a stable way of picking an icon file - it just picks the first file matching the pattern provided in the desktop file. If the desktop file only has a stem, anything will do; if it has a filename and an extension, the first file matching those in the icon paths will be ok, even if it's an 8x8 icon. It would be great if an icon with the best resolution was chosen instead (svg, if there's svg; or the largest png up to, say, 512x512). That implies reading the icon; but at the very least, it would be great to see the same icon being picked every time, otherwise AppImage generation may sometimes work, sometimes break as in the example above.

**Comment by TheAssassin** [comment]
I guess there are two solutions to this:

- pick the "best" icon available (priorities: svg, then resolutions in descending order)
- recognize if there's an icon already, and skip deployment then, allowing the user to manually pick one

**Comment by KitsuneRal** [comment]
In fact, https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html has the exact icon lookup algorithm.

**Comment by TheAssassin** [comment]
Would you like to send a PR implementing this lookup feature?

**Comment by KitsuneRal** [comment]
Actually, to begin with, why does this code copies just one icon file rather than all found?

**Comment by TheAssassin** [comment]
Because it's about the deployment into the AppDir root directory. Check https://docs.appimage.org/reference/appdir.html. You need to have exactly one icon in the root dir.

**Comment by KitsuneRal** [comment]
Ah, right. Would it be reasonable to assume that this icon is a kind of fallback? I suppose desktop integration would still look into the AppImage and find an appropriate icon. My point is that if the application happens to have several icons for different themes then some choice among themes should be made, and it seems that the safest choice is to just fallback to `hicolor`, which the Icon Theme Spec mandates to exist.

**Comment by KitsuneRal** [comment]
And one more question: how much should I preserve the C++ API? Do plugins make use of it? Specifically, I'd like to turn `std::vector<bf::path> AppDir::deployedIconPaths()` to something like `bf::path findIcon(std::string pattern)` where `pattern = iconEntry.value()`. Does it make sense and would it break anything?

**Comment by TheAssassin** [comment]
> Would it be reasonable to assume that this icon is a kind of fallback? I suppose desktop integration would still look into the AppImage and find an appropriate icon.

Yes, `.DirIcon` and the named icon file are meant for stuff like thumbnailers. libappimage's integration looks into `usr/share/icons` first, and falls back to the icons in the root dir. The AppDir root stuff is more of a ROX Filer legacy thing.

>  which the Icon Theme Spec mandates to exist.

Don't take that spec too literally... Practically all desktops deviate in some way. But anyway, `hicolor` is typically used if present.

> And one more question: how much should I preserve the C++ API? Do plugins make use of it? Specifically, I'd like to turn std::vector<bf::path> AppDir::deployedIconPaths() to something like bf::path findIcon(std::string pattern) where pattern = iconEntry.value(). Does it make sense and would it break anything?

The API is exposed to plugins and used most prominently by linuxdeploy-plugin-qt. It makes no sense to remove methods.

I don't know why you don't just use it, as the existing lookup does? It is just a convenience function to list all files in `usr/share/{icons,pixmaps}`. I think you just have to modify `deployDesktopFileAndIcon()` to use the highest-quality icon it can find. I don't mind extracting some of it into an `AppDir::findIcon` method, but it should be named more precisely. Specifically, you want to implement a `findSuitableHighestQualityIcon(const std::string& pattern)` or something similar.

I suggest to implement this method inside `class AppDirRootSetup` to avoid extending the `AppDir` interface with another method (which violates the SRP even more). If it ever had to, it could still be moved over there. But the goal is to actually reduce the amount of violating methods in `AppDir`.

**Comment by KitsuneRal** [comment]
> > which the Icon Theme Spec mandates to exist.
> 
> Don't take that spec too literally... Practically all desktops deviate in some way. But anyway, `hicolor` is typically used if present.
Well, `/usr/share/icons/hicolor` actually was adopted as a sort of "default" icons location across a wide variety of distros, from my experience. Of course not everything that is specced gets actually adopted.

> > And one more question: how much should I preserve the C++ API? Do plugins make use of it? Specifically, I'd like to turn std::vectorbf::path AppDir::deployedIconPaths() to something like bf::path findIcon(std::string pattern) where pattern = iconEntry.value(). Does it make sense and would it break anything?
> 
> The API is exposed to plugins and used most prominently by linuxdeploy-plugin-qt. It makes no sense to remove methods.
> 
> I don't know why you don't just use it, as the existing lookup does? It is just a convenience function to list all files in `usr/share/{icons,pixmaps}`. I think you just have to modify `deployDesktopFileAndIcon()` to use the highest-quality icon it can find. I don't mind extracting some of it into an `AppDir::findIcon` method, but it should be named more precisely. Specifically, you want to implement a `findSuitableHighestQualityIcon(const std::string& pattern)` or something similar.
> 
> I suggest to implement this method inside `class AppDirRootSetup` to avoid extending the `AppDir` interface with another method (which violates the SRP even more). If it ever had to, it could still be moved over there. But the goal is to actually reduce the amount of violating methods in `AppDir`.

Ok, I think I got it. The reason why `AppDir::deployedIconPaths()` doesn't work is that it returns the list of _regular files_ (not even icon files) in _no particular order_ that is not stable across runs. In theory I could go through that list _again_ in an attempt to find the best icon; but I'd rather only select icons, in the first place. Given that the only actual thing needed from `AppDir` is `AppDir::path()` it should not be a big problem to implement that within `AppDirRootSetup`.

**Comment by KitsuneRal** [comment]
One thing though is that I found it to be quite a bit of a chore to completely properly look into `index.theme`, identify directories for the requested size (which one, actually - 128x128?), then order those directories by their "distance" from the requested size... Unless you already have some facility code to read `index.theme` - but I guess you don't?

**Comment by KitsuneRal** [comment]
A low-hanging fruit I think I managed to reap is to at limit the lookup to png/svg/xmp (in that order) extensions, in each directory. This would at least fix a problem for my case where occasionally a non-compliant svgz could have been picked. Which file is picked (even whether it's a png or svg) is still unstable between runs. Lexicographic ordering of the directories might help (coincidentally, that would get 128x128 icons to the top of the list most of the time).

**Comment by TheAssassin** [comment]
Ignore `index.theme` and just look for icons yourself, I'd say. I haven't seen a single `index.theme` in any AppImage. You can assess the "quality" of icons based on their resolutions, with scalable ones being on top, then resolution in descending order.

> no particular order that is not stable across runs

Why not improve `deployedIconPaths`? Two things could be done to greatly improve it: first, only list icons in paths that comply with the icon theme spec, not "files in `usr/share/...`. No fancy algorithms needed, I'd say, just check the filenames. Error checking is not necessarily a task for linuxdeploy (e.g., an invalid/empty file can be permitted, it's sufficient to just parse the resolution from the directory names and sort them).
Second, sort the results by priority (i.e., quality). That way, the first entry is always the highest-quality icon.
Ignoring non-graphics files would be a nice bonus.

This method can always be improved further, so I'd start like that, and keep the amount of changes maintainable.

**Comment by KitsuneRal** [comment]
> Ignore `index.theme` and just look for icons yourself, I'd say. I haven't seen a single `index.theme` in any AppImage. 

Because `index.theme` is not supposed to come with applications, it's a part of an icon theme (even `hicolor`). It's just metadata on directories where actual icons reside, in particular, how far icons in a particular directory can/should be scaled (usually up to twice for raster files and more for scalable). But yeah, for our intents and purposes I guess it's an overkill.

> You can assess the "quality" of icons based on their resolutions, with scalable ones being on top, then resolution in descending order.

That's extreme nitpicking but the spec actually says that (within a given directory) PNGs should be considered first, with SVGs following if supported. I guess this is due to relatively limited SVG support 15 years ago and the desire to provide a stable source of icons. On the other hand, without knowing the display the icon's going to be shown, it might be prudent to prioritise SVGs.

> > no particular order that is not stable across runs
> 
> Why not improve `deployedIconPaths`? 

Because it collects _all_ files in `$DESTDIR/usr/share/icons` and `$DESTDIR/usr/share/pixmaps`, which is a bit different semantics from what I'd like (look specifically for application icons - hence `$DESTDIR/usr/share/icons/*/apps` - and only png/svg/xpm). It's only used from one place (I searched throughout GitHub) so I thought I'd rather replace it with a different function - and if it's a different function, I could just as well just lookup the needed icon file on the file system, using the `iconEntry.value()` as a parameter - instead of harvesting a list of files in `AppDir` and selecting the "best" of them in `AppDirRootSetup`. But I'm new to the codebase so can't comment if that breaks SRP between the two classes.

Alternatively, I can keep the current API shape but instead of `listFilesInDirectory` only collect files matching the mentioned criteria, as you suggest; that would change its semantics to something more like `deployedAppIconPaths()` though.

> Error checking is not necessarily a task for linuxdeploy (e.g., an invalid/empty file can be permitted, it's sufficient to just parse the resolution from the directory names and sort them).

Yes, same page here.

> Second, sort the results by priority (i.e., quality). That way, the first entry is always the highest-quality icon.

The spec doesn't make it easy to do this part, unfortunately; first, it is rather insistent that the requesting party knows the size it needs; second, aside from exact match, there's a distance-based fallback algorithm; don't know if I'll get to that.

The problem with too large icons is that thumbnailers usually fail scaling, say, a 256x256 icon down to 24x24 - even for SVGs, unless they are specifically made to support a very wide variety of sizes. We can't predict the target environment but I guess 64x64 is a reasonable middle ground for that case.

> Ignoring non-graphics files would be a nice bonus.

Filtering by extension already goes a long way in putting non-graphics files aside.

**Comment by KitsuneRal** [comment]
After thinking further - actually, my suggested approach wouldn't really help with picking the best quality icon; returning a list of candidates looks better in this regard.

**Comment by TheAssassin** [comment]
Well, you actually need to walk the directory anyway to fetch all candidates, then pick one. Returning a list ordered by priority descendingly to me seems more useful than just returning a single icon. Picking the first entry is _really_ easy, too.

The existing method can be fixed to return only graphics. Then, in the `AppDirRootSetup` class, it's relatively easy to filter and order the list.

**Comment by KitsuneRal** [comment]
Yes, that's what I got down to in the end. I think I'll leave prioritising to `AppDirRootSetup`; but first off `deployedIconPaths()` will return what the icon theme spec (and other linuxdeploy parts, actually) expect for icons.

**Comment by TheAssassin** [comment]
Sounds good!
