### ISSUE TITLE
Replace libmagic with more robust solution

### ISSUE THREAD

**Issue by TheAssassin** [linuxdeploy/linuxdeploy#17]
Deploying libmagic causes issues on newer distributions (>= trusty (build system)). Since we only use it to detect ELF files, we should write our own, magic bytes based check, and get rid of libmagic for the purpose.

**Comment by sithlord48** [comment]
on arch when running --init-appdir the following happens
>-- Deploying dependencies for existing files in AppDir -- 
/etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
terminate called after throwing an instance of 'linuxdeploy::util::magic::MagicError'
  what():  Failed to load magic data: could not find any valid magic files!
Aborted (core dumped)
