### ISSUE TITLE
Segmentation fault when running on different system

### ISSUE THREAD

**Issue by saedrna** [linuxdeploy/linuxdeploy#170]
Hi, 

I have sucessfully deploy an application into AppDir format. My application is built in an virtual anaconda environment and deployed with the linuxdeploy-plugin-qt. My system is latest linux mint (e.g., ubuntu 20.04). I have sucessfully run the AppDir in another linux mint system, but failed to run it on ubuntu 18.04.

I would like to ask if there are some special tricks for deploy on different systems?

Han

**Comment by TheAssassin** [comment]
https://docs.appimage.org/introduction/concepts.html#build-on-old-systems-run-on-newer-systems

**Comment by saedrna** [comment]
I see. Thx!
