### ISSUE TITLE
How can i build an aarch64 version

### ISSUE THREAD

**Issue by hsinor** [linuxdeploy/linuxdeploy#175]
I only find release version of x86_64 and i686. I want build a AppImage for aarch64, what should i do?

**Comment by MatNieuw** [comment]
I have built an autotools version as normal executable, suitable for aarch64. It is not an AppImage. I can send you the code, if you want.

**Comment by lucasfernog** [comment]
I'm also interested in this. Can we change the workflow to do it?

**Comment by lucasfernog** [comment]
Would be closed by #189

**Comment by Korkman** [comment]
@TheAssassin Any update on this?

**Comment by K4CZP3R** [comment]
I was able to create docker image containing linuxdeploy which works on arm64: https://github.com/K4CZP3R/linuxdeploy-tauri-arm64

**Comment by semmjon** [comment]
Cool, thanks, I'll test it right away :D

**Comment by dcarr45** [comment]
@K4CZP3R very new to this so my apologies, but I've produced the `squashfs-root` that's the output of the last RUN command in your Dockerfile sequence and I've been banging my head against the wall trying to produce the equivalent of `linuxdeploy-aarch64.AppImage` (the one that's not currently distributed).

I assume all the files I need are there in `/executables` of the resultant Docker container, but if you get a chance could you please clarify how one would produce the executable that'd match the usage of `linuxdeploy-x86_64.AppImage`? I'm trying to replace the missing arm64 executable that'd be called in this [bundler script](https://github.com/tauri-apps/tauri/blob/dev/tooling/bundler/src/bundle/linux/templates/appimage#L80) used by [Tauri](https://tauri.app/v1/guides/building/linux)

**Comment by andy5995** [comment]
Duplicate of https://github.com/linuxdeploy/linuxdeploy/issues/108

**Comment by dcarr45** [comment]
I had some success just following the [linuxdeploy:ci/build.sh](https://github.com/linuxdeploy/linuxdeploy/blob/master/ci/build.sh) and [linuxdeploy-plugin-appimage:ci/build-appimage.sh](https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/blob/master/ci/build-appimage.sh) in an arm64 Docker container - it got a little hairy due to the apparent circular dependency between those two builds where they each download the latest version of the other, but I was able to produce what appears to be a usable `linuxdeploy-aarch64.AppImage`

**Comment by TGP17** [comment]
> I had some success just following the [linuxdeploy:ci/build.sh](https://github.com/linuxdeploy/linuxdeploy/blob/master/ci/build.sh) and [linuxdeploy-plugin-appimage:ci/build-appimage.sh](https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/blob/master/ci/build-appimage.sh) in an arm64 Docker container - it got a little hairy due to the apparent circular dependency between those two builds where they each download the latest version of the other, but I was able to produce what appears to be a usable `linuxdeploy-aarch64.AppImage`

Can you provide the build instructions that worked for you?

**Comment by yusiwen** [comment]
Any updates? Need arm64/aarch64 badly

**Comment by neildavis** [comment]
Offering potential help on this for `armhf` & `aarch64`. See my [comment](https://github.com/linuxdeploy/linuxdeploy/pull/189#issuecomment-1792294465) on #189

**Comment by TheAssassin** [comment]
Just for the record, an ARM version is on the way. I'm just fiddling with the build process, but it's working locally already.

**Comment by TheAssassin** [comment]
Build is working now. I need to clean the branch up and merge it into the main branch. I should be able to do it tonight.

**Comment by TheAssassin** [comment]
It's done. Binaries are available. Feedback welcome!

**Comment by andy5995** [comment]
@TheAssassin Thanks for completing this! I am finally getting around to trying it. I'm having a spot of trouble though.

`./linuxdeploy-aarch64.AppImage: cannot execute binary file: Exec format error`

I seem to recall an issue where you mentioned using sed to change a few bytes, which worked in another case for me, but I can't find it.

I'm trying it with a Dockerfile. Here's the workflow output

https://github.com/netpanzer/netpanzer/actions/runs/7499142351/job/20415397490#step:8:435


The [actual workflow/yml file](https://github.com/netpanzer/netpanzer/blob/master/.github/workflows/docker-build-env.yml)

And [the Dockerfile](https://github.com/netpanzer/netpanzer/blob/master/support/docker/Dockerfile-build-env_focal)

**Comment by andy5995** [comment]
> @TheAssassin Thanks for completing this! I am finally getting around to trying it. I'm having a spot of trouble though.
> 
> `./linuxdeploy-aarch64.AppImage: cannot execute binary file: Exec format error`
> 
> I seem to recall an issue where you mentioned using sed to change a few bytes, which worked in another case for me, but I can't find it.

Found it. I also found the the `dd` method you mentioned in another ticket here.

I believe this is fixed in https://github.com/netpanzer/netpanzer/commit/241a664ada9bb8fe52000e360b043c579162590e
