### ISSUE TITLE
Question: deploy apps with own shared libs

### ISSUE THREAD

**Issue by DexterMagnific** [linuxdeploy/linuxdeploy#178]
Hi all,

I'm trying to deploy my app which have its own shared libs with no success.
My "make install" installed the binary in AppDir/usr/bin and the libraries in AppDir/usr/lib

But when I try to bundle my app, I get this:

```
ERROR: Could not find dependency: libMyLib.so.1 
ERROR: Failed to deploy dependencies for existing files
```

I checked the lib is present in AppDir/usr/lib.

I can't find any option in linuxdeploy that specifies custom library locations.

Can you help ?
Thanks

**Comment by TheAssassin** [comment]
This has been asked before more than once.

You need to have your build system set `DT_RUNPATH` ("rpath") correctly on all the libraries you build or `export LD_LIBRARY_PATH=...` to whatever location your `.so` files reside in. linuxdeploy uses `ldd` to resolve dependencies.

**Comment by DexterMagnific** [comment]
Hi,

Thank you. This worked.
Believe me I searched this in the doc and on the web with no success.
I think this particular point deserves an entry in the documentation.

**Comment by TheAssassin** [comment]
Please don't hesitate to submit a PR to the AppImage docs or to this repo's README. I agree that this is a recurring question, even if rarely asked. I don't have time to do this, and there's hardly any external contributions, especially docs wise, unfortunately.
