### ISSUE TITLE
Separate 32-bit and 64-bit libraries

### ISSUE THREAD

**Issue by MCMrARM** [linuxdeploy/linuxdeploy#18]
In my usecase, I have mixed 64-bit and 32-bit binaries (some of the application is 32-bit due to usage of compiled code I have no control over). Preferably most of the application would be compiled as a 64-bit one, with just the 32-bit components being 32-bit.
However, this causes issues as the directory for the libraries is shared between 32-bit and 64-bit.

**Comment by TheAssassin** [comment]
Link to example AppImage: https://transfer.sh/OTRQS/Minecraft_Bedrock_Edition_launcher-x86_64.AppImage

**Comment by TheAssassin** [comment]
I think the only viable way would be to put libraries into different, architecture dependent directories.

CC @probonopd maybe you have some ideas how this can be fixed.

**Comment by probonopd** [comment]
Why do you think 32-bit libraries need to be in a different directory than 64-bit libraries? I am not sure whether you can have a 32-bit and a 64-bit version of the same library and mix and match between them.

Why is it not OK to have everything inside the AppImage be 32-bit?

**Comment by TheAssassin** [comment]
@probonopd well, the whole issue is about the fact that libraries with different architectures can *not* be used together. If you look at what distributions do, you won't find a single one putting libraries for more than one architecture into the same library directory, there's always arch specific ones (e.g., `/usr/lib{32,64,}`, `/usr/lib/{x86_64,i386,armhf}-linux-gnu`, etc.). Putting them into the same directory might perhaps work if all filenames were carrying an architecture tag.

**Comment by TheAssassin** [comment]
The use case here is: A 64-bit application shall be packaged together with a 32-bit helper application, both use similar libraries with different architectures.

**Comment by TheAssassin** [comment]
According to the [FHS](http://www.pathname.com/fhs/pub/fhs-2.3.html), libraries are supposed to put into separate directories, depending on their architecture. For instance, 32-bit libraries on a 64-bit system should go into a `/usr/lib32` directory.

In my opinion we should follow that recommendation, and make linuxdeploy aware of 32-bit libraries and applications. For 64-bit AppImages, we can just put the libraries into `/usr/lib32`, for 32-bit ones, we should continue to put the 32-bit libraries into `/usr/lib` (but we could as well follow the same strategy as on 64-bit to keep things simple).

**Comment by probonopd** [comment]
My 2 cents: edge case, for which it is not  worth complicating our code base to automate AppDir generation.

In edge cases like this, manual AppDir creation is preferable. I don't want `/usr/lib32` directories to appear, especially since not even distributions can agree on a path for these.

Let's keep things simple. The author's edge case can be solved by a script that produces an AppDir.

**Comment by TheAssassin** [comment]
> especially since not even distributions can agree on a path for these.

Therefore the idea to follow the FHS, an actual _standard_ which defines what I described. See also https://docs.appimage.org/reference/appdir.html#conventions.

**Comment by TheAssassin** [comment]
I decided to go the way to actually support "32-bit on 64-bit" by creating a `usr/lib32` directory for 32-bit libraries. Like on the base system, 32-bit binaries can safely be put into `usr/bin/`. It's a lot more straightforward for us to do this. Also it gives us a chance to implement some sort of "library architecture check" to prevent e.g., mixing ARM binaries into x86_64, etc.
