### ISSUE TITLE
need help with cmake: qmake worked but cmake fails on AppVeyor

### ISSUE THREAD

**Issue by Light-Wizzard** [linuxdeploy/linuxdeploy#182]
I am switching from qmake to cmake, everything was working prior to this, cmake is the only thing that changed, this is on AppVeyor, the link for the source is below, I ran this with and without the .pro file, yet I see this message `Using qmake`, and wonder if it has anything to do with it, or is that internal, I tried to convert my .pro file into cmake the best I could, it runs on both Linux and Windows on my machines, is there something cmake does differently?

```
-- Running input plugin: qt -- 
[qt/stdout] Using qmake: /home/appveyor/Qt/5.15.2/gcc_64/bin/qmake 
[qt/stdout] Using Qt version:  5.15.2  ( 5 ) 
[qt/stdout] Found Qt modules:  
[qt/stdout] Extra Qt modules:  
[qt/stdout] ERROR: Could not find Qt modules to deploy 
ERROR: Failed to run plugin: qt (exit code: 1) 
Command exited with code 1
```
build script: https://github.com/Light-Wizzard/QtAppVeyor/blob/main/scripts/build_script.sh

```
qmake "${REPO_ROOT}";

cmake "${REPO_ROOT}" -G "Unix Makefiles" -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX="AppDir";

Tried this with no help, which is correct?
cmake "${REPO_ROOT}" -G "Unix Makefiles" -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX="/usr";
```

I do not have any build errors, and the program runs on Linux and Windows.

I noticed you create the AppDir folder Creating directory AppDir/usr/bin/, this gets confusing from, I have a usr folder structure I build for Qt Installer framework, and my pro file pointed to /usr, I thought this might work `set(EXECUTABLE_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/usr)`, but no matter what I try I get the same error, I have tried many things, google did not help.

I know I am missing something, like the proper folder layout, I am not sure how qmake translate this

```
unix {
    isEmpty(PREFIX) {
        PREFIX = /usr
    }
    target.path         = "$${PREFIX}/bin"
    shortcutfiles.files = "usr/share/applications/$${TARGET}.desktop"
    shortcutfiles.path  = usr/share/applications
    data.files         += "usr/share/icons/hicolor/48x48/apps/$${TARGET}.png"
    data.path           = usr/share/pixmaps
    INSTALLS           += shortcutfiles
    INSTALLS           += data
    INSTALLS           += target
    macx {
        RC_FILE = macos/Icon.icns
    }
}

# This is how I translated it
set(EXECUTABLE_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/usr)
```

GitHub: https://github.com/Light-Wizzard/QtAppVeyor

AppVeyor: https://ci.appveyor.com/project/Light-Wizzard/qtappveyor

This cmake works in Windows with windeployqt.

Thanks, Flesh

**Comment by TheAssassin** [comment]
https://github.com/Light-Wizzard/QtAppVeyor/blob/main/scripts/build_script.sh#L132

CMake uses `DESTDIR`. I'm sure your build log will reveal that nothing actually got installed into `AppDir` (I haven't had a look yet). Change the name of the env var and try again.

**Comment by Light-Wizzard** [comment]
I tried this with no help, but I am not sure this is even correct, but it worked for qmake, and sudo made no difference:

```
make install INSTALL_ROOT=AppDir;
or
sudo INSTALL_ROOT=AppDir make install;
to
sudo DESTDIR=AppDir make install;
and
make install DESTDIR=AppDir;
```

Thanks, Flesh

**Comment by TheAssassin** [comment]
You are supposed to call it like `make install DESTDIR=AppDir` with CMake. Again, `INSTALL_ROOT` is for qmake only, while `DESTDIR` works on many other tools including CMake.

**Comment by TheAssassin** [comment]
Looks like your project just doesn't have anything to install anyway? https://ci.appveyor.com/project/Light-Wizzard/qtappveyor/build/job/2dvctdf2g67popgk#L1198
The issue here is a CMake one, not a linuxdeploy one. There is just nothing to deploy.

**Comment by TheAssassin** [comment]
Feel free to follow up once you figured out your CMake install config.

By the way, `-DCMAKE_INSTALL_PREFIX="/usr"` is required. And please stop placing `;` in every line in shell scripts...

**Comment by Light-Wizzard** [comment]
I changed cmake to 

```
set(EXECUTABLE_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/usr/bin)

ls /home/appveyor/projects/qtappveyor/usr/bin
QtAppVeyor
```

The Application is being created where I told it, so it does not seem to be cmake, my question now is should this be /usr/bin instead of ${PROJECT_SOURCE_DIR}/usr/bin?

I am sure this is what the issue is, so I need to know the right way, where should I physically be putting these files?

I started writing bash in the 70's, then in the military during the 80s and 90s, then the Government in 2000s, and you always had to use ; and I have OCD, so I cannot stop it, and shellcheck reminds me if I do forget.

Thanks, Flesh

**Comment by TheAssassin** [comment]
Check out https://cmake.org/cmake/help/latest/command/install.html. Setting a random variable won't make anything work.

**Comment by Light-Wizzard** [comment]
Huge help, thanks, got past that issue, and I can deal with the link error I have now, I have always avoided cmake, now I have no choice, so those two issues were all I was missing. 

I was dealing with a fire today, I live on a mountain that is on fire right now, so I keep making mistakes, fire is under control and should be out by tomorrow.

I am writing this App to make it easier for programmers to use AppVeyor, but I am distracted by cancer and today a fire, so I hope to have this working someday soon, now to clean up this code.

Thanks, Flesh

**Comment by Light-Wizzard** [comment]
One more question, I am missing something here:

```
-- Set runtime path of "AppDir/usr/bin/QtAppVeyor" to ""
'/home/appveyor/Qt/5.15.2/gcc_64/lib/libQt5Core.so.5' -> 'usr/lib/libQt5Core.so.5'

# it did not pick up on Sql

-- Deploying dependencies for existing files in AppDir -- 
Deploying dependencies for ELF file AppDir/usr/bin/QtAppVeyor 
ERROR: Could not find dependency: libQt5Sql.so.5 
ERROR: Failed to deploy dependencies for existing files 
```

I have it defined in cmake as below

```
find_package(Qt5 COMPONENTS REQUIRED Core Gui Widgets Sql PrintSupport Network LinguistTools LinguistTools Concurrent)
set(QT5_LIBRARIES Qt5::Core Qt5::Gui Qt5::Widgets Qt5::Sql Qt5::PrintSupport Qt5::Network)
target_link_libraries(${TARGET} ${QT5_LIBRARIES})
```

I found the executable where it should be here AppDir/usr/bin/QtAppVeyor but the library folders are missing, do they need to be there, I have no idea why this is, but I am sure it is a cmake issue, have you seen this before, I cannot find it googling.

Thanks, Flesh
