### ISSUE TITLE
CRLF line endings in .desktop file displays confusing error messages

### ISSUE THREAD

**Issue by saisasidhar** [linuxdeploy/linuxdeploy#183]
I ended up in this weird situation by accident while using a templating engine to generate files required for linuxdeploy, the template for this .desktop file had CRLF endings

Here's log output demonstrating an unrelated "RROR" message (not ERROR 😄)
~~~
-- Deploying files into AppDir root directory --
Deploying custom AppRun:  /home/tars/workbench/test-appimage/build_resources/CustomAppRun.sh
Deploying file /home/tars/workbench/test-appimage/build_resources/CustomAppRun.sh to AppDir/AppRun
Copying file /home/tars/workbench/test-appimage/build_resources/CustomAppRun.sh to AppDir/AppRun
Deploying files to AppDir root using desktop file: AppDir/usr/share/applications/test.desktop
Deploying desktop file to AppDir root: AppDir/usr/share/applications/test.desktop
Creating symlink for file AppDir/usr/share/applications/test.desktop in/as AppDir
 RROR: Could not find suitable icon for Icon entry: test
~~~

My .desktop file looks as follows
~~~
[Desktop Entry]
Version=0.1.0
Name=test
Icon=test
Type=Application
Exec=python3.7
Categories=ConsoleOnly;
Terminal=true
~~~

What distracted me from the actual CRLF problem for a while was that linuxdeploy was symlinking .desktop file within AppRun just fine, but failing at icon. 

I've fixed my line endings since but I think it would be nice for linuxdeploy application to either convert file endings or display an error message that files have CRLF line endings and abort.

**Comment by jerkstorecaller** [comment]
There's tons of weird behavior if your files have CRLF line endings. I think I once edited /etc/sysctl.conf from a Windows system and scp'ed it to a Linux system, and the OS stopped booting because a **configuration file** had some CRLF! IIRC bash (might have been sh) can't run scripts that have CRLF. 

"dos2unix myfile.desktop" is a simple fix.

**Comment by TheAssassin** [comment]
I think we can conclude that when working on a unixoid system, one should adhere to Unix standards. Therefore, nothing to fix here.
