### ISSUE TITLE
Remove "--app-name myapp"

### ISSUE THREAD

**Issue by probonopd** [linuxdeploy/linuxdeploy#19]
Remove "--app-name myapp" since the information is contained in the desktop file.

**Comment by TheAssassin** [comment]
That's not quite precise. We should remove any kind of app name based magic and _instead_ rely on what is provided in the desktop file.

This requires some restructuring. For now, I'd deprecate the parameter (i.e., instead of using the information, print a deprecation warning, which will be removed eventually when the final fix is pushed; this way, users are informed about the change and can take action before we remove it entirely).

**Comment by probonopd** [comment]
Sounds like a plan. For me it's an advantage when one does not _need_ that parameter. (I'd be fine if it stayed for compatiblity reasons as an undocumented parameter for a while.)

**Comment by TheAssassin** [comment]
Just found another use case in which this parameter was useful. For AppImageUpdate, we've had multiple desktop files in the AppDir already, and using `--app-name` linuxdeploy was able to use the right one for deploying AppRun etc.

I think we need to make sure linuxdeploy does accept parameters within the AppDir for `-d` at least.

**Comment by probonopd** [comment]
Can't we point `linuxdeploy` to _the_ desktop file? Like you can invoke `linuxeployqt` by pointing to the desktop file that shall be used as the main entrypoint.

**Comment by TheAssassin** [comment]
@probonopd linuxdeploy uses the AppDir as main argument for good reasons. We created a consistent "API" by requiring linuxdeploy and all the plugins to implement the `--appdir <appdir>` parameter. Normally, you just have one desktop file anyway. Perhaps it makes sense to look into `/usr/bin` for binaries and then look for a suitable desktop file or something.

**Comment by probonopd** [comment]
The reason why linuxdeployqt was switched from using the AppDir as the argument to the desktop file as the argument was exactly the fact that there may well be (for valid reasons even) more than one desktop file in the AppDir and you need a way to specify which one should be used as the main entrypoint.
