### ISSUE TITLE
linuxdeploy errs saying PrefersNonDefaultGPU is a non-standard Desktop Entry key

### ISSUE THREAD

**Issue by txtsd** [linuxdeploy/linuxdeploy#192]
[Link to GitHub Actions log](https://github.com/txtsd/PolyMC/runs/5084594197?check_suite_focus=true#step:14:8207)

```
[appimage/stdout] /home/runner/work/PolyMC/PolyMC/install/org.polymc.polymc.desktop: error: file contains key "PrefersNonDefaultGPU" in group "Desktop Entry", but keys extending the format should start with "X-"
```

But `PrefersNonDefaultGPU` IS a valid key in the [Desktop Entry Spec](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys).

**Comment by TheAssassin** [comment]
You're wrong here, this is an appimagetool issue. Please open an issue in appimagetool and/or linuxdeploy-plugin-appimage. appimagetool must ship a newer `desktop-file-validate`.

**Comment by txtsd** [comment]
Thanks for pointing me in the right direction.
