### ISSUE TITLE
Create AppImage on recent distribution and allow running on older by removing glibc version information

### ISSUE THREAD

**Issue by dgcor** [linuxdeploy/linuxdeploy#216]
From what I understood, the reason AppImages created on newer distributions don't run is because of glibc adding versioning to the export table in the elf.

Newer versions of patchelf have a `--clear-symbol-version` that removes the version information from the function signature.

reference: https://stackoverflow.com/questions/2856438/how-can-i-link-to-a-specific-glibc-version

perhaps linuxdeploy can add an optional flag that tries to do something like this on the main binary and all the libs.

**Comment by TheAssassin** [comment]
You got this wrong. AppImages would typically not run because the glibc version on the system they run on is simply too old. gcc is pretty good at adding version markers only when they're really necessary (if you use just legacy APIs, apparently, your binary may even run on older systems).

What's the point if it won't run anyway? Instead of crashing with a meaningful message, the result will be some segfault. I don't see any advantage in this.

**Comment by dgcor** [comment]
Understood, so that means that if I compile with a newer glibc but only use malloc/free, then it should work in older versions without any change?

**Comment by TheAssassin** [comment]
Depends whether glibc has received a newer algorithm and you depend on its semantics. As said, it's up to the compiler.

The easiest way to make sure your application runs on an older system is to build on an older system.

For libstdc++-only upgrades (e.g., using Ubuntu 18.04 with the `ubuntu-toolchain-r` PPA to install an up-to-date `g++-10`), you can use https://github.com/linuxdeploy/linuxdeploy-plugin-checkrt.

Another way to using a newer compiler on an old distro is `devtoolset-9` for CentOS 7. The compilers provided by these toolchains use some special linking magic (apparently they can link libc/libstdc++ statically in parts while maintaining compatibility to the original CentOS 7 versions; not an expert, just a user) to provide CentOS 7 ABI compatible binaries. This is demonstrated in https://github.com/AppImage/AppImageBuild/. Note that you then likely have to build all your dependencies yourself, unless you can directly use at least some CentOS 7 provided packages.

**Comment by TheAssassin** [comment]
Anyway, I don't see any realistic use case for this. The chance for it to work is tiny. It most likely creates issues for users, though. Developers might use it incorrectly and produce broken AppImages. And linters like https://github.com/TheAssassin/appimagelint won't be able to do their job any more. Closing therefore.
