### ISSUE TITLE
Build errors: missing files

### ISSUE THREAD

**Issue by efp** [linuxdeploy/linuxdeploy#218]
Greetings,

My fist time trying to use linuxdeploy. With a fresh clone, I get:

> CMake Error at CMakeLists.txt:47 (include):
>   include could not find load file:
> 
>     /home/efp/Code/linuxdeploy-master/lib/cmake-scripts/include-or-build-gtest.cmake
> 
> 
> CMake Error at lib/CMakeLists.txt:5 (add_subdirectory):
>   The source directory
> 
>     /home/efp/Code/linuxdeploy-master/lib/linuxdeploy-desktopfile
> 
>   does not contain a CMakeLists.txt file.

It's plain to see those files are not in the source tree. 

After that, there's

> CMake Error at src/core/CMakeLists.txt:15 (FetchContent_Declare):
>   Unknown CMake command "FetchContent_Declare".

There's no `include(FetchContent)` in the CMakeList. Perhaps it's supposed to be in one of the missing files. 

P.S. an INSTALL file, describing how to build it, would be nice. There are no build instructions anywhere in the documentation either.

**Comment by TheAssassin** [comment]
You do not need to build this project typically. And your problem is the classic "I forgot to add `--recursive` to the clone command". Either use `git clone --recursive` or use `git submodule update --init --recursive`.

**Comment by efp** [comment]
Thanks for the response, like I said, first time user... and just the sort of thing it would be helpful to document :)

**Comment by TheAssassin** [comment]
See also https://docs.appimage.org/packaging-guide/from-source/linuxdeploy-user-guide.html.
