### ISSUE TITLE
linuxdeploy do not run in docker containers (needs GLIBC_2.34)

### ISSUE THREAD

**Issue by iTrooz** [linuxdeploy/linuxdeploy#220]
When i run the release AppImage in a docker container (I tried Ubuntu 16.04, 18.04 and 20.04) I get this error :
```
root@c7893656a00a:/mnt# ./linuxdeploy-x86_64.AppImage
[appimagelauncher-binfmt-bypass/interpreter] AppImageLauncher not found at /usr/bin/AppImageLauncher, launching AppImage directly: ./linuxdeploy-x86_64.AppImage
[appimagelauncher-binfmt-bypass/lib] WARNING: could not find preload library path, using temporary file
./linuxdeploy-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/appimagelauncher-preload-2CLQVA.so)
```

The same executable seems to run fine in an Ubuntu 18.04/20.04 virtual machine

If this is a normal behavior, how should we package appimages in the oldest-supported system, if not with a container ?

**Comment by TheAssassin** [comment]
Please try without AppImageLauncher installed.

**Comment by iTrooz** [comment]
AppImageLauncher wasn't installed on the containers

I just re-tried with a new Ubuntu 18.04 container (`docker run -it --rm ubuntu:18.04 bash`), and ran these commands after creation :
```
$ apt update
$ apt install wget
$ wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
$ chmod +x linuxdeploy-x86_64.AppImage
$ ./linuxdeploy-x86_64.AppImage 
```

It does the same error

**Comment by TheAssassin** [comment]
> AppImageLauncher wasn't installed on the containers

Yes, I know. I never claimed that. You need to uninstall it on the host.

**Comment by iTrooz** [comment]
Removing AppImageLauncher from the host indeed fixed it, thanks !
