### ISSUE TITLE
Could not find dependency (but it's there)

### ISSUE THREAD

**Issue by aurelienpierre** [linuxdeploy/linuxdeploy#238]
Following up on #237, I tried to build on Ubuntu 20.04 using [the same script](https://github.com/aurelienpierreeng/ansel/blob/master/.ci/ci-script-appimage.sh). Note that the script was tested on Fedora 37 and produces a workable AppImage on Arch and Fedora, as long as the libc version is recent enough.

It errors with this log : 
https://github.com/aurelienpierreeng/ansel/actions/runs/3778151831/jobs/6422390124#step:7:2482

```
ERROR: Could not find dependency: libansel.so 
```

The problem is that, as https://github.com/aurelienpierreeng/ansel/actions/runs/3778151831/jobs/6422390124#step:7:2231 shows, it is there in the AppDir : 

```
# Make Install output
-- Installing: ../AppDir/usr/lib/x86_64-linux-gnu/ansel/libansel.so

# LinuxDeploy output
Deploying shared library /home/runner/work/ansel/ansel/src/AppDir/usr/bin/../lib/x86_64-linux-gnu/ansel/libansel.so
WARNING: Could not find copyright files for file /home/runner/work/ansel/ansel/src/AppDir/usr/bin/../lib/x86_64-linux-gnu/ansel/libansel.so using dpkg-query 
```

Here is the build log for that script if I run it locally on Fedora : 
[build.log](https://github.com/linuxdeploy/linuxdeploy/files/10304812/build.log)

**Comment by aurelienpierre** [comment]
I tried to set the runtime path explicitely for `libansel.so`:
```
-- Installing: ../AppDir/usr/lib/x86_64-linux-gnu/ansel/libansel.so
-- Set runtime path of "../AppDir/usr/lib/x86_64-linux-gnu/ansel/libansel.so" to "$ORIGIN/../lib/x86_64-linux-gnu/ansel"
```
It doesn't change anything.

**Comment by aurelienpierre** [comment]
Fixed at compilation time by forcing the libdir explicitly:
```
cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib64
```

**Comment by TheAssassin** [comment]
Another workaround is to `export LD_LIBRARY_PATH=.../AppDir/usr/lib` before calling linuxdeploy. But the proper solution will always be to set the rpath correctly with CMake.
