### ISSUE TITLE
Checking if a path is a directory is broken

### ISSUE THREAD

**Issue by samshawelmtek** [linuxdeploy/linuxdeploy#244]
I've been having QML plugins deploy as `Plugin/libplugin.so/libplugin.so` and `Plugin/qmldir/qmldir`, which is clearly wrong. I was able to determine it's how the copy to path is being determined if it has a trailing slash or not.

Checking for a trailing slash is broken here:
https://github.com/linuxdeploy/linuxdeploy/blob/dee359b179844e5d0dbe449e559a7dc3c402a32b/src/core/appdir.cpp#L161

If you replace it with `to.string().back()` like in https://github.com/linuxdeploy/linuxdeploy/blob/dee359b179844e5d0dbe449e559a7dc3c402a32b/src/core/appdir.cpp#L343 then it's all good.

**Comment by TheAssassin** [comment]
Please send a PR.
