### ISSUE TITLE
version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by efa** [linuxdeploy/linuxdeploy#248]
I'm try to learn AppImage packaging.
My app use GTK3 so using linuxdeploy with gtk plugin, I do not know if I need to open the issue here or on gtk plugin, lets try here before, sorry for misplace in case.

`$ linuxdeploy-x86_64.AppImage -e ./reSolveGuiLinux64 --appdir AppDir -p gtk -i ReSolve.png -d reSolve.desktop --output appimage`
it generate a 30 MB package with a lot of deps files, but I see glibc and libm are banned.
That work well on my Debian 11.

I uploaded the generated ‘appImage’ named ‘ReSolveGui-76a44d5-x86_64.AppImage’ here:
https://github.com/efa/ReSolve/releases/tag/v0.10.09h

Anyway the AppImage do not start on a Debian 10:
```
$ ReSolveGui-76a44d5-x86_64.AppImage
/tmp/.mount_ReSolvxlYaY3/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_ReSolvxlYaY3/AppRun.wrapped)
/tmp/.mount_ReSolvxlYaY3/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_ReSolvxlYaY3/usr/bin/../lib/libgtk-3.so.0)
/tmp/.mount_ReSolvxlYaY3/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_ReSolvxlYaY3/usr/bin/../lib/libcairo.so.2)
/tmp/.mount_ReSolvxlYaY3/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_ReSolvxlYaY3/usr/bin/../lib/libpixman-1.so.0)
/tmp/.mount_ReSolvxlYaY3/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_ReSolvxlYaY3/usr/bin/../lib/libpng16.so.16)
/tmp/.mount_ReSolvxlYaY3/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by /tmp/.mount_ReSolvxlYaY3/usr/bin/../lib/libsystemd.so.0)
```

I tryed also to unpack the AppImage, running AppRun or the binary sr/bin/reSolveGui give same error.

Note:
Debian 11 has GLIBC 2.31
Debian 10 has GLIBC 2.28

What is the reason to ban glibc?
Is there an option to avoid glibc ban?

**Comment by TheAssassin** [comment]
See https://docs.appimage.org/introduction/concepts.html#build-on-old-systems-run-on-newer-systems. You need to build on Debian 10. It'll run on 11.

**Comment by efa** [comment]
work, thank you
