### ISSUE TITLE
cannot load /usr/lib 

### ISSUE THREAD

**Issue by newyorkthink** [linuxdeploy/linuxdeploy#260]
![image](https://github.com/linuxdeploy/linuxdeploy/assets/87791643/1bb8800e-f28b-43c8-b29e-53ad7c7d4999)
![image](https://github.com/linuxdeploy/linuxdeploy/assets/87791643/85c4c068-6a2e-41d4-bfe2-cff09fb71d59)

it have lib but , the appimage cannot load lib in appimage inline

**Comment by TheAssassin** [comment]
Problem is unclear. Please add more details. Otherwise, please talk to the vendors of your application.

**Comment by newyorkthink** [comment]
> Problem is unclear. Please add more details. Otherwise, please talk to the vendors of your application.

hi, is not the appimage have problem , is have some more appimage cannot load lib 

for example :zathura

this is open pdf tools., use sudo apt-get install zathura

when i use linuxdeploy builld it, 
```
./linuxdeploy.AppImage --appdir AppDir --output appimage

```

![image](https://github.com/linuxdeploy/linuxdeploy/assets/87791643/bafe2a0a-8f3b-4642-a313-cbda1138709f)

its have same situation

**Comment by TheAssassin** [comment]
That's a bug in your application. If you are not the developer, please ask them. You cannot just throw pre-built software and hope it will work. They most likely need to do some work to support AppImage. I cannot and do not want to provide support for third party software.
