### ISSUE TITLE
wrong execution realpath

### ISSUE THREAD

**Issue by efa** [linuxdeploy/linuxdeploy#262]
I created an AppImage of my SDL2 binary "WL":
https://github.com/efa/Wilderland
with the commands:
```
$ wget -nv "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage"
$ chmod +x linuxdeploy-x86_64.AppImage
$ linuxdeploy-x86_64.AppImage -e WL --appdir AppDir -i Wilderland.png -d Wilderland.desktop --output appimage
```

The generated AppImage once runt, show this::
`realpath()='/home/efa/c/Wilderland2.10b_2023-11-27_Linux_x86_64_64bit.AppImage'`
by this code:
```
   char absPath[PATH_MAX];
   realpath(argv[0], absPath);
   printf("realpath()='%s'\n", absPath);
```
instead of something like:
`realpath()='/tmp/.mount_WilderlandHASH/usr/bin/WL'`
I got with other applications (in that case generated by GTK plugin) packaged as AppImage.

This in turn, cause the AppImage binary to quit as it cannot load any assets packaged in AppImage

Please help me figure out whats is wrong here

**Comment by efa** [comment]
where I have this trouble is https://github.com/efa/Wilderland where I used SDL2.

On https://github.com/efa/ReSolve made with GTK3 and AppImage.gtk-plugin, realpath(argv[0]) return
'/tmp/.mount_ReSolveHASH/usr/bin/ReSolveGUI' on all platforms.

**Comment by TheAssassin** [comment]
In any case, this is not a bug in linuxdeploy.

**Comment by efa** [comment]
do you discourage the use of $APPDIR ?

**Comment by efa** [comment]
I solved with:
https://github.com/efa/Wilderland/blob/master/WL.c#L1984
this work for both --appimage-extract* commands, thank you.
Note: --appimage-extract-and-run seems not documented anywhere
