### ISSUE TITLE
Can't seem to build on Arch

### ISSUE THREAD

**Issue by Ketrel** [linuxdeploy/linuxdeploy#269]
From a fresh checkout  

1. `git submodule update --init --recursive`  
2. `mkdir _build && cd _build`  
3. `cmake .. 2>&1 | tee _output_001.txt`  ( Link: https://termbin.com/0kte Attached below as well)
4. `make -j1 2>&1 | tee _output_002.txt` ( Link: https://termbin.com/jhne Attached below as well)

This is error I'm seeing   
```
/usr/bin/ld: cannot find -lpng16: No such file or directory
/usr/bin/ld: cannot find -ljpeg: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [tests/simple_executable/CMakeFiles/simple_executable_static.dir/build.make:98: tests/simple_executable/simple_executable_static] Error 1
make[1]: *** [CMakeFiles/Makefile2:1763: tests/simple_executable/CMakeFiles/simple_executable_static.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

`ls -l /usr/lib | grep -e 'png16' -e 'jpeg' | sort` 

```
drwxr-xr-x   2 root root      4096 Sep  6 00:28 openjpeg-2.5
lrwxrwxrwx   1 root root        11 Jun 29  2023 libpng.so -> libpng16.so
lrwxrwxrwx   1 root root        12 Oct 18 02:03 libjpeg.so -> libjpeg.so.8
lrwxrwxrwx   1 root root        16 Oct 18 02:03 libjpeg.so.8 -> libjpeg.so.8.3.2
lrwxrwxrwx   1 root root        17 May 25  2020 libjpeg.so.62 -> libjpeg.so.62.2.0
lrwxrwxrwx   1 root root        17 Oct 18 02:03 libturbojpeg.so -> libturbojpeg.so.0
lrwxrwxrwx   1 root root        19 Jun 29  2023 libpng16.so -> libpng16.so.16.40.0
lrwxrwxrwx   1 root root        19 Jun 29  2023 libpng16.so.16 -> libpng16.so.16.40.0
lrwxrwxrwx   1 root root        21 Oct 18 02:03 libturbojpeg.so.0 -> libturbojpeg.so.0.3.0
-rwxr-xr-x   1 root root    235392 Jun 29  2023 libpng16.so.16.40.0
-rwxr-xr-x   1 root root    317184 May 25  2020 libjpeg.so.62.2.0
-rwxr-xr-x   1 root root    702400 Oct 18 02:03 libjpeg.so.8.3.2
-rwxr-xr-x   1 root root    854208 Oct 18 02:03 libturbojpeg.so.0.3.0
```

[_output_001.txt](https://github.com/linuxdeploy/linuxdeploy/files/13866130/_output_001.txt)
[_output_002.txt](https://github.com/linuxdeploy/linuxdeploy/files/13866131/_output_002.txt)

**Comment by Ketrel** [comment]
This was due to Arch not providing the static libraries.

**Comment by T0maas** [comment]
But what is the solution? Where can I disable static build. Which CMakeLists.txt sets static build? I could remove that static build setting, but I found lot of CMakeLists.txt inside various subdirs.

**Comment by Ketrel** [comment]
You have to have the static libraries in question, that meant I had to build them.

**Comment by TheAssassin** [comment]
Non-static build is not supported. I have time to maintain the Dockerized build environment but not any more anyway, so please do as @Ketrel and figure it out yourself.

@Ketrel thanks for your reply, highly appreciated.
