### ISSUE TITLE
linuxdeploy complains of missing appdir parameter even when it was actually provided in the command

### ISSUE THREAD

**Issue by mdear** [linuxdeploy/linuxdeploy#271]
Ok, I'm back, still trying to take a Qt-6 demo executable cross-compiled on an x86_64 build VM for target aarch64 (Dice 3D example) and package it for deployment to an aarch64 platform (i.MX8 DualXPlus and QuadXPlus processors on CrossControl V700 and V1200 products).  

I've now built Yocto Poky Kirkstone branch (which has the gcc-3.5 that is compatible with Qt-6) against a qemuarm64 architecture and run it on a nested aarch64 build VM.  

I tried my packaging command:
`./linuxdeploy-aarch64.AppImage --desktop-file /home/ccs/Qt/Examples/Qt-6.6.0/demos/build-dice-Docker_Image_ktechnology_v700_sdk_3_2_0_0_qt_6_4_1_f7d1a901936a-Debug/dice.desktop --appdir /home/ccs/Qt/Examples/Qt-6.6.0/demos/build-dice-Docker_Image_ktechnology_v700_sdk_3_2_0_0_qt_6_4_1_f7d1a901936a-Debug/dice.AppDir --executable /home/ccs/Qt/Examples/Qt-6.6.0/demos/build-dice-Docker_Image_ktechnology_v700_sdk_3_2_0_0_qt_6_4_1_f7d1a901936a-Debug/dice --icon-file /home/ccs/Qt/Examples/Qt-6.6.0/demos/build-dice-Docker_Image_ktechnology_v700_sdk_3_2_0_0_qt_6_4_1_f7d1a901936a-Debug/dice.png --output appimage  --plugin qt --library=/home/ccs/Qt/Projects/CortexBuilds/V700/Qt-6.4.1/lib --library=/home/ccs/Qt/Projects/CortexBuilds/glibc_2.35_out/lib --library=/lib --library=/usr/lib --library /home/ccs/Qt/Projects/CortexBuilds/V700/sysroots/cortexa35-poky-linux/lib --library /home/ccs/Qt/Projects/CortexBuilds/V700/sysroots/cortexa35-poky-linux/usr/lib`

... and got a failing code, apparently due to a missing "--appdir" parameter (which, as you can see, I have provided).  

Any idea what's wrong here, and how to work around it ?
[linuxdeploy_strace_failed.log](https://github.com/linuxdeploy/linuxdeploy/files/14143469/linuxdeploy_strace_failed.log)

Thanks !

https://www.dropbox.com/scl/fi/o6qro4xd03wps4ln3pjbs/linuxdeploy_strace_failed_log?rlkey=hqthaggge0voeeaf7s6vwjp8p&dl=0

**Comment by mdear** [comment]
I worked around this issue so will close the ticket.

**Comment by TheAssassin** [comment]
You should share your solution, though.
Generally speaking, `--appdir` is usually the first parameter to be passed. I cannot imagine why it would not work the way you tried, though.
