### ISSUE TITLE
runtime-loaded libraries fail to deploy because of inter-dependency

### ISSUE THREAD

**Issue by goeland86** [linuxdeploy/linuxdeploy#282]
We're using linuxdeploy and we have a few 3rd-party libraries which are loaded at runtime if necessary.
There's a few of these library files, but essentially the difficulty seems to be an inter-dependency between the .so files.

```
>>> Deploying shared library builds/App-Desktop_Qt_5_15_2_GCC_64bit-Release/Setup/App/App/lib/libutils.so
>>> Deploying dependencies for ELF file builds/App-Desktop_Qt_5_15_2_GCC_64bit-Release/Setup/App/App/lib/libutils.so 
>>> Deploying dependencies for ELF file builds/App-Desktop_Qt_5_15_2_GCC_64bit-Release/Setup/App/App/lib/liblcs2dll.so 
>>> ERROR: Could not find dependency: libutils.so 
>>> ERROR: Failed to deploy library:  builds/App-Desktop_Qt_5_15_2_GCC_64bit-Release/Setup/App/App/lib/liblcs2dll.so 
>>> >>> 
```

Any idea what could be causing this? In this case we absolutely do not want to load these .so files into the binary if they're not needed, but I can't build the AppImage with them in this way. I'm specifically passing in each of the 9 .so files with a --library parameter to the command-line.

The folder paths have been anonymized, but everything is coherent as shown.

**Comment by TheAssassin** [comment]
linuxdeploy uses plain old ldd to look up dependencies. Try `ldd` on your library. It should show the missing dependency, too.

When libraries are missing like this, it's usually a sign of either a broken installation or a broken installer. Libraries should have `DT_RUNPATH` (aka rpath) set to make sure that tools like `ldd` or the system's loader can find libraries in "non-standard" locations.

You need to find out where the library is and `export LD_LIBRARY_PATH` accordingly. linuxdeploy should make sure that once deployed into the AppDir, loading works. Please note that this is a workaround, though.

**Comment by goeland86** [comment]
Thanks. As mentioned, these are provided to us by a 3rd-party, so we have little control over how they're set up. I do see the `ldd` missing dependency as well. I will try to set the `DT_RUNPATH` correctly, as they're in the same directory. I hope this will be easy.

**Comment by TheAssassin** [comment]
Well, if they're third party, I'd probably not worry too much about it and just set `LD_LIBRARY_PATH`.

**Comment by goeland86** [comment]
The build is fixed, thanks for the help! The rest is now managing the Github action runners to behave, but I think I shall manage that after a bit of sleep.
