### ISSUE TITLE
Segmentation fault on Github Actions

### ISSUE THREAD

**Issue by Chocobo1** [linuxdeploy/linuxdeploy#289]
Our CI is starting to see segmentation faults since yesterday and everything was fine [before](https://github.com/qbittorrent/qBittorrent/actions/workflows/ci_ubuntu.yaml).
The error:
```
/home/runner/work/_temp/4c135550-565b-4eaf-810e-f5d2b9304c44.sh: line 1:  6239 Segmentation fault      (core dumped) ./linuxdeploy-static-x86_64.AppImage --appdir qbittorrent --plugin qt
```

Build log: https://github.com/qbittorrent/qBittorrent/actions/runs/10231408970/job/28315246726#step:14:25
Workflow file: https://github.com/qbittorrent/qBittorrent/actions/runs/10231408970/workflow#L159

Maybe it could be related to some recent updates?
https://github.com/linuxdeploy/linuxdeploy/commits/master/
https://github.com/linuxdeploy/linuxdeploy-plugin-qt/commits/master/

Also I noticed that our CI is running on `ubuntu-latest` which is `ubuntu-22.04` while `linuxdeploy*` was built on `ubuntu-20.04`. AFAIK our CI were using the `static` variation of `linuxdeploy` so we should be immune to the OS, library, etc. difference right?

**Comment by Samueru-sama** [comment]
I'm also getting this. Rolling back to 1-alpha-20240109-1 fixes the issue in the meantime.

**Comment by TheAssassin** [comment]
I'll rebuild the latest binaries as there has been a segfault bug in the runtime.

**Comment by TheAssassin** [comment]
Please try the latest continuous release.

**Comment by Chocobo1** [comment]
>I'll rebuild the latest binaries as there has been a segfault bug in the runtime.

Was it related to this? https://github.com/AppImage/type2-runtime/issues/51
Anyway our CI don't fail now. Thanks!

**Comment by TheAssassin** [comment]
Yep, exactly that one.
