### ISSUE TITLE
Parameter to add exclude patterns

### ISSUE THREAD

**Issue by TheAssassin** [linuxdeploy/linuxdeploy#29]
Some users might want linuxdeploy to skip certain libraries in addition to the official [excludelist](https://github.com/AppImage/AppImages/blob/master/excludelist). We should add a parameter for that purpose.

**Comment by phoerious** [comment]
Would it be possible to do it the other way round as well and allow for explicit includes? We need to ship a custom libgpg-error.so, but it's excluded by linuxdeploy.

**Comment by phoerious** [comment]
My current workaround is this:

    linuxdeploy ... --library=$(ldconfig -p | grep x86-64 | grep -oP '/[^\s]+/libgpg-error\.so\.\d+$' | head -n1)

**Comment by TheAssassin** [comment]
I think it's easier to provide that snippet, as it's quite an edge case. Searching for libraries is not trivial, and we'd need multiple implementations for multiple platforms. That's more of a documentation issue. Thanks for providing that snippet.

Regarding the excludelist, it's maintained carefully, and you should normally rely on it. A configuration option would be very easy to misuse. If you have comments about it, please open an issue in the AppImages repository.

**Comment by phoerious** [comment]
We need this libgpg-error, because we rely on a newer version of libgcrypt, which also requires a newer version of libgpg-error.so, so it's vital that we include it. It's definitely legacy support (legacy as in Ubuntu < 17.10), so I'm fine with keeping my workaround, but I'd assume there will always be some edge cases like this.

**Comment by TheAssassin** [comment]
Please open a separate issue so we can consider adding such a "convenience feature" as e.g., a parameter. However, I still think providing a snippet in the README e.g. is better (especially since the snippet is architecture-aware).

**Comment by knapsu** [comment]
This feature would be really useful. Any estimate when there would be a possibility to exclude certain libraries? It blocks me from moving from `linuxdeployqt` to `linuxdeploy`. Maybe adding an `--exclude-library` parameter would be an option?

`libnss3.so` and `libnssutil3.so` are a real troublemaker. These are not on the official blacklist though
https://raw.githubusercontent.com/probonopd/AppImages/master/excludelist

**Comment by TheAssassin** [comment]
It'd probably be better viable to use an environment variable so plugins using liblinuxdeploy will respect the setting, too.

**Comment by tamlok** [comment]
What is the status of this issue? Could we have a `--exclude-library` option like `linuxdeployqt`? Come into the same issue with `libnss3.so` and `libnssutil3.so`.

**Comment by txtsd** [comment]
I'm trying to include JDK in my AppImage, and it fails to deploy with this:
```
-- Deploying dependencies for existing files in AppDir -- 
Deploying dependencies for ELF file install/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jexec 
Skipping deployment of blacklisted library /lib/x86_64-linux-gnu/libc.so.6 
Deploying dependencies for ELF file install/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libsaproc.so 
Skipping deployment of blacklisted library /lib/x86_64-linux-gnu/libthread_db.so.1 
Skipping deployment of blacklisted library /lib/x86_64-linux-gnu/libdl.so.2 
Deploying dependencies for ELF file install/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libunpack.so 
ERROR: Could not find dependency: libjvm.so 
ERROR: Failed to deploy dependencies for existing files 
Error: Process completed with exit code 1.
```
The JDK is installed via apt-get and the folder is copied over.
