### ISSUE TITLE
Failed to launch on Ubuntu LTS 24 : AppImages require FUSE to run

### ISSUE THREAD

**Issue by narcdev** [linuxdeploy/linuxdeploy#290]
Hey,

I tried to execute the binarie from the continuous build on Ubuntu LTS 24. 
(https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage)

But it fails with the following error : 

```
./linuxdeploy-x86_64.AppImage
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run.
```
libfuse2 is not available on Ubuntu 24, it comes with libfuse3.

Any idea on how to solve this ? 

Thanks a lot

**Comment by Samueru-sama** [comment]
If you are using linuxdeploy in a CI it is better to just run it with the `--appimage-extract-and-run` flag, even if you actually install the fuse package it can break in the future if the name of the package changes, like it happened recently as it changed name to `libfuse2t64`

Now if you want to make an appimage that doesn't depend on libfuse2, on that case you would need to use the static runtime, normally the quick easy way would be using this [appimagetool ](https://github.com/probonopd/go-appimage) however as of a few hours ago I noticed that the runtime links changed, so I'm not sure now linuxdeploy will use the static runtime now on.

**Comment by narcdev** [comment]
Thanks a lot for your answer.

I currently use linuxdeploy in a CI to get all dependancies of my qt project. 
And then I use [appimagetool](https://github.com/AppImage/appimagetool) to generate the appimage.

I've check [go-appimage](https://github.com/probonopd/go-appimage) as suggested, but it doesn't support QtWebEngine bundle. And I need it for my project. 

Maybe I should try to build linuxdeploy from source on Ubuntu 24 ?

**Comment by Samueru-sama** [comment]
>I've check [go-appimage](https://github.com/probonopd/go-appimage) as suggested, but it doesn't support QtWebEngine bundle. And I need it for my project.

You don't have to use go-appimage to deploy, you only need to turn the AppDir into an appimage, what deploys the dependencies into the AppDir would be linuxdeploy instead, or another alternative, there are several.

Linuxdeploy can also generate the appimage without the need to use an external appimagetool, but it will create an appimage that depends on libfuse2, you would instead only use linuxdeploy to deploy (get all the dependencies of the qt project) and then you turn that AppDir into an appimage with go-appimage.

but

It is likely this issue will be fixed in the future if it hasn't already, I'm saying because less than 24 hour ago the appimagetool you just linked is also now pulling the static runtime by default and you don't have to use go-appimagetool anymore.

>Maybe I should try to build linuxdeploy from source on Ubuntu 24 ?

If you say this because linuxdeploy needs libfuse2, run linuxdeploy instead with the `--appimage-extract-and-run` flag which will make it do its job even if there is no fuse2 or 3 on the system, less things to worry about if the CI in the future gets a broken fusermount or no longer ships it even.

**Comment by TheAssassin** [comment]
> but it will create an appimage that depends on libfuse2

That is going to change relatively soon now that we've made some progress in the AppImage project on the topic of static runtimes...

**Comment by TheAssassin** [comment]
Also, please try the `static` build which uses the static runtime already and should run on any platform.

**Comment by narcdev** [comment]
Thanks a lot for all the explaination !

> If you say this because linuxdeploy needs libfuse2, run linuxdeploy instead with the `--appimage-extract-and-run` flag which will make it do its job even if there is no fuse2 or 3 on the system, less things to worry about if the CI in the future gets a broken fusermount or no longer ships it even.

I've tried with the `--appimage-extract-and-run` flag, and it fails in another way ! But seems libfuse is still needed..

Here is the log : 
```
./linuxdeploy-x86_64.AppImage --appimage-extract-and-run --appdir /var/local/builds/workspace/24lts/AppDir --verbosity=0

linuxdeploy version 1-alpha (git commit ID f12a4a0), GitHub actions build 275 built on 2024-08-02 23:42:58 UTC
DEBUG: Searching for plugins in directory /var/local/builds/workspace/24lts
DEBUG: Doesn't match plugin regex, skipping: /var/local/builds/workspace/24lts/.gitlab-ci-actions-tagCumu.pl
DEBUG: Doesn't match plugin regex, skipping: /var/local/builds/workspace/24lts/linuxdeploy-x86_64.AppImage
DEBUG: Doesn't match plugin regex, skipping: /var/local/builds/workspace/24lts/appimagetool-x86_64.AppImage
DEBUG: Probing plugin /var/local/builds/workspace/24lts/linuxdeploy-plugin-qt-x86_64.AppImage
DEBUG: subprocess /var/local/builds/workspace/24lts/linuxdeploy-plugin-qt-x86_64.AppImage --plugin-api-version failed with exit code 1
DEBUG: stdout: (no output)
DEBUG: stderr: dlopen(): error loading libfuse.so.2

AppImages require FUSE to run.
You might still be able to extract the contents of this AppImage
if you run it with the --appimage-extract option.
See https://github.com/AppImage/AppImageKit/wiki/FUSE
for more information

terminate called after throwing an instance of 'std::logic_error'
  what():  subprocess /var/local/builds/workspace/24lts/linuxdeploy-plugin-qt-x86_64.AppImage --plugin-api-version failed with exit code 1
```

**Comment by narcdev** [comment]
> Also, please try the `static` build which uses the static runtime already and should run on any platform.

Yes I've tried witht the 'static' build here :  [linuxdeploy-static-x86_64.AppImage ](https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-static-x86_64.AppImage)

But it directly crash with a segfault (core dumped)

**Comment by Samueru-sama** [comment]
@narcdev 

The error is likely that the plugin also needs to be launched with the --appimage-extract-and-run flag.

Test setting the env variable `export APPIMAGE_EXTRACT_AND_RUN=1` and that way you don't have to pass the flag.

>But it directly crash with a segfault (core dumped)

[That's a different recent issue.](https://github.com/linuxdeploy/linuxdeploy/issues/289), you will have use to use `1-alpha-20240109-1` in the meantime.

**Comment by narcdev** [comment]
> The error is likely that the plugin also needs to be launched with the --appimage-extract-and-run flag.
> 
> Test setting the env variable `export APPIMAGE_EXTRACT_AND_RUN=1` and that way you don't have to pass the flag.

Great ! It works with this ! Thanks a lot.

> That's a different recent issue, you will have use to use 1-alpha-20240109-1 in the meantime.

Ok, thanks for the information. I'll try with it.
