### ISSUE TITLE
[BUG] The current continuous build seems to cause sqlite in-memory error

### ISSUE THREAD

**Issue by pbek** [linuxdeploy/linuxdeploy#291]
The current continuous build seems to cause sqlite in-memory error https://github.com/pbek/QOwnNotes/issues/3073.

![Screenshot_2024-08-05_15-12-07](https://github.com/user-attachments/assets/e660c326-0bcc-4147-a20f-6dbbda1e15b2)

Falling back to 1-alpha-20240109-1 did work.

**Comment by Samueru-sama** [comment]
Can you try again? there was a different error causing a segfault that was fixed, maybe it is related to this.

**Comment by pbek** [comment]
Yes, thank you very much! It works again!
