### ISSUE TITLE
`libpipewire-0.3.so.0` should be excluded

### ISSUE THREAD

**Issue by rtbo** [linuxdeploy/linuxdeploy#292]
same as for libjack, it has to match the API/ABI of the server installed on the target system.
In addition, libpipewire-0.3.so comes with a heavy set of plugins and configuration files.

Plugins could be packaged in the AppImage, but configuration files should come from the target system, and the last fallback  of the search path is hard coded in the `libpipewire-0.3.so` binary.
So AppImage  running on a system that did not customize configuration would likely fail to find the right configuration file.

Anyway, excluding it from the AppDir is for the best.

**Comment by probonopd** [comment]
Wouldn't that mean that the AppImage will not run on systems without Pipewire?

Pipewire cannot be expected to be present on each target system (distribution) imho.

**Comment by rtbo** [comment]
yes, same as libjack.
Ideally, `libpipewire-0.3.so` should be packaged, but the loader should load in priority the one installed on the host system, and fallback to the one in the image.
This would allow apps to run more reliably, and load the fallback version with which you can detect that pipewire isn't installed and fallback to another sound system. 

MuseScore has such a fallback mechanism. I don't know if it is a common practice though.
See [AppRun.in](https://github.com/musescore/MuseScore/blob/master/buildscripts/packaging/Linux%2BBSD/portable/AppRun.in) and this [PR](https://github.com/musescore/MuseScore/pull/23939/files).

**Comment by TheAssassin** [comment]
Looks like you'd want to create a plugin like https://github.com/darealshinji/linuxdeploy-plugin-checkrt for both libjack and libpipewire. But the discussion whether to exclude this library needs to be done in https://github.com/AppImageCommunity/pkg2appimage/pull/556.
