### ISSUE TITLE
Premature termination when packing KiCad

### ISSUE THREAD

**Issue by antoniovazquezblanco** [linuxdeploy/linuxdeploy#34]
I was using the following commands to try and build an appimage containing the KiCad EDA suite:
```
mkdir -p build
cd build
cmake -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr ../
make -j$(nproc) --output-sync
make test
make install DESTDIR=AppDir
LD_LIBRARY_PATH=$(pwd)/AppDir/usr/lib/x86_64-linux-gnu/ linuxdeploy --appdir AppDir -d $(pwd)/AppDir/usr/share/applications/kicad.desktop --output KiCad-$(git describe)
```

I was using the following docker image: `antoniovazquezblanco/kicad-builder`

When executing the last command the following error aborted the proces prematurely:
```
Deploying dependencies for ELF file AppDir/usr/lib/x86_64-linux-gnu/kicad/plugins/3d/libs3d_plugin_oce.so 
terminate called after throwing an instance of 'linuxdeploy::core::elf::ElfFileParseError'
  what():  Invalid magic bytes in file header
Aborted (core dumped)
```

How should I proceed to debug this?

Thanks in advance

**Comment by TheAssassin** [comment]
@antoniovazquezblanco apparently the ELF magic bytes `\177ELF` are missing in your file. Can you manually verify that (check `xxd myfile | head -n1` and/or post it here)?

**Comment by antoniovazquezblanco** [comment]
After your message recompilation seems to have fixed the issue. I am sorry for the noise.

Thank you very much
