### ISSUE TITLE
Build worked 7 weeks ago, now fails with newer linuxdeploy version

### ISSUE THREAD

**Issue by r41d** [linuxdeploy/linuxdeploy#36]
I built a Makefile to bundle my application 7 weeks ago and it worked fine.
For that I used `linuxdeploy version 1-alpha (git commit ID 83a9690), Travis build 158 built on 2018-09-04 12:36:16 UTC`
Now, I wanted to bundle it again, grabbed the latest linuxdeploy AppImage (Travis build 189), and the process fails.
OK, the `--app-name` parameter seems to be removed (despite still being listed in the documentation (https://docs.appimage.org/packaging-guide/from-source/linuxdeploy-user-guide.html)) so I got rid of that.
But after that it still fails with the error 
```
[appimage/stderr] appimagetool, continuous build (commit d185526), build 1855 built on 2018-10-07 20:18:45 UTC
[appimage/stderr] Desktop file not found, aborting
ERROR: Failed to run plugin: appimage 
```
but my call to linuxdeploy looks like this:
```
	./linuxdeploy-x86_64.AppImage -v1 \
			--appdir ${APPDIR} \
			--output appimage \
			--executable app \
			--desktop-file app.desktop \
			--icon-file app.png
```
Well, I specify which desktop-file to use, plus it worked 7 weeks ago, any idea what is going on here?

**Comment by r41d** [comment]
The appimagetool version seems to also have changed, I compared both the linuxdeploy code for the aforementioned git commits and for the old and current appimagetool versions (`git diff 6f44629 d185526`) but wasn't able to find the place where the desktop file handling was changed to that it now fails for me :/

**Comment by TheAssassin** [comment]
@r41d what you use to build AppImages is the [AppImage plugin](https://github.com/linuxdeploy/linuxdeploy-plugin-appimage). Perhaps something changed there?

It seems strange to me that it doesn't work any more for you. Can you share your AppImage build script, please?

**Comment by r41d** [comment]
This is my full makefile: https://gist.github.com/r41d/9d7ed7c6ec34da1611272e07a9e4f2b0
The only change I made (from the 7-weeks-ago-working-version) was removing the `--app-name` parameter

**Comment by TheAssassin** [comment]
You can deploy your AppRun using `--custom-apprun`, so you can skip the manual copying. You can further `export OUTPUT=my.AppImage`.

Other than that it seems right. What project are you building there? I need to try to reproduce that issue...

**Comment by r41d** [comment]
I think found a workaround, after adding
```
	cp app.desktop ${APPDIR}/
	cp app.png ${APPDIR}/
```
to my Makefile (before building the image) it works.
I thought that `--desktop-file` and `--icon-file` should've done the trick - i.e. that it puts the stuff to the AppDir and manages the paths - but that wasn't the case.
Previous (7 weeks ago) versions of linuxdeploy/appimagetool seem to have handled things differently / more gracefully, so that it worked back then.

**Comment by TheAssassin** [comment]
> I thought that --desktop-file and --icon-file should've done the trick - i.e. that it puts the stuff to the AppDir and manages the paths - but that wasn't the case.

They _do_ normally. You should provide a log. Perhaps there's warnings you missed.

**Comment by azubieta** [comment]
@r41d Hi! Is it possible for you to share the source code so I can try to reproduce the error locally?

**Comment by TheAssassin** [comment]
@azubieta no need for source code, just create a simple AppDir with a desktop file and icon already in `usr/...`, and an AppRun file in the root directory, and you'll reproduce the issue.

**Comment by azubieta** [comment]
It seems that everything related to desktop, icon and AppRun deployment is done [here](https://github.com/linuxdeploy/linuxdeploy/blob/2f7ad201f1df3c9b399c228ef861e9f871db5206/src/main.cpp#L254_L303) and is a bit broken.

**Comment by TheAssassin** [comment]
Define "broken". It does work fine for "most" use cases. But as said before, its current workflow is a bit limiting. Therefore, a restructuring might be appropriate.

**Comment by azubieta** [comment]
According to this [line](https://github.com/linuxdeploy/linuxdeploy/blob/2f7ad201f1df3c9b399c228ef861e9f871db5206/src/main.cpp#L256) the existing AppRun will be overwritten. But the code that is suposed to do that is [here](https://github.com/linuxdeploy/linuxdeploy/blob/2f7ad201f1df3c9b399c228ef861e9f871db5206/src/main.cpp#L294) where is not reachable.

Also [this](https://github.com/linuxdeploy/linuxdeploy/blob/f1690cc2a361e63316233f93e16e4e95b1b4d356/src/core/appdir.cpp#L650) function makes too many decisions that doesn't correspond to AppDir. As it's mostly for inspecting and deploying not for making decisions.

**Comment by TheAssassin** [comment]
Please reopen if the issue persists. Should be fixed now, though.

**Comment by r41d** [comment]
Yes, with the current linuxdeploy version (`git commit 9d25fee, Travis build 261`) it now works with the `--desktop-file` and `--icon-file` parameters.
Thanks everyone :)
