### ISSUE TITLE
Build AppImages binaries used in test cases in runtime

### ISSUE THREAD

**Issue by azubieta** [linuxdeploy/linuxdeploy#37]
Currently, we have real AppImage files inside the tests/data dir which could have been built from sources in "test time" using the same `linuxdeploy`.

This will reduce the project download size and ease future changes to the AppImage files used during the tests.

**Comment by TheAssassin** [comment]
> This will reduce the project download size

No, it will in fact enlarge that. Git doesn't delete old objects. You will always clone them subsequently. Once you commit the crime to commit large blobs, you cannot get rid of them unless you rewrite the history. That isn't possible after publishing the history once any more.

> ease future changes to the AppImage files used during the tests

We don't use any AppImages in the tests? In fact, we don't have any tests here? WIP in #33.

**Comment by TheAssassin** [comment]
This should've been posted in another issue tracker. Closing as invalid.
