### ISSUE TITLE
AppImage failed caused by Icon

### ISSUE THREAD

**Issue by obiwankennedy** [linuxdeploy/linuxdeploy#53]
Hi all,

This is the command, I run in the goal to get an AppImage:

`./linuxdeploy-x86_64.AppImage --appdir AppDir -e AppDir/usr/bin/rolisteam -i ../../rolisteam.svg -d ../../rolisteam.desktop --plugin qt --output appimage`

this is the content of "rolisteam.desktop" file:
```
[Desktop Entry]
X-AppInstall-Package=rolisteam
X-AppInstall-Section=universe

Type=Application
Name=Rolisteam
Icon=/usr/share/icons/hicolor/scalable/apps/rolisteam.svg
Version=1.9.0
Comment=Manage your role playing game
Exec=/usr/bin/rolisteam
Terminal=false
Categories=Game;
```

This is the error, I got:
```
-- Deploying icons -- 
Deploying icon ../../rolisteam.svg 
Deploying copyright files for file ../../rolisteam.svg 
WARNING: Could not find copyright files for file ../../rolisteam.svg using dpkg-query 

-- Deploying desktop files -- 
Deploying desktop file ../../rolisteam.desktop 

-- Copying files into AppDir -- 
Copying file ../../rolisteam.desktop to AppDir/usr/share/applications/rolisteam.desktop 
Copying file ../../rolisteam.svg to AppDir/usr/share/icons/hicolor/scalable/apps/rolisteam.svg 

-- Deploying files into AppDir root directory -- 
Deploying desktop file: AppDir/usr/share/applications/rolisteam.desktop 
Deploying desktop file to AppDir root: AppDir/usr/share/applications/rolisteam.desktop 
Creating symlink for file AppDir/usr/share/applications/rolisteam.desktop in/as AppDir 
ERROR: Could not find suitable icon for Icon entry: /usr/share/icons/hicolor/scalable/apps/rolisteam.svg
```

I don't get why it could not find suitable icon. It deployed the icon. It should be able to do all the stuff it needs.
Does it not support SVG file ? What am i doing wrong ?
Why the AppImage building is stopped by such a little error. Is there a way to continue on this error ?

Thank you for your time.
Regards.

**Comment by TheAssassin** [comment]
> Icon=/usr/share/icons/hicolor/scalable/apps/rolisteam.svg

Absolute paths in desktop files are not allowed, neither are extensions. Just change the entry to `Icon=rolisteam` and it should work.

**Comment by obiwankennedy** [comment]
Ok, I replaced /usr/bin/rolisteam by rolisteam and it goes further.

**Comment by TheAssassin** [comment]
Rule of thumb: never put absolute paths into the desktop file. Not even when using `make install` etc. The desktop file spec contains some algorithm descriptions how to find icons, binaries etc. by their names.

You should try `desktop-file-validate` by the way. It will at least log warnings if not errors if you're doing something incorrectly.

**Comment by michalfapso** [comment]
Thanks, @TheAssassin! The `desktop-file-validate` warned me about incorrect line endings. I created my .desktop file on windows, so my `ERROR: Could not find suitable icon for Icon entry: qt_test_appimage` was solved by `dos2unix qt_test_appimage.desktop`
