### ISSUE TITLE
Allowed characters in desktop files

### ISSUE THREAD

**Issue by antoniovazquezblanco** [linuxdeploy/linuxdeploy#62]
I am trying to build a KiCad AppImage but fails with the following errors:

```
-- Deploying desktop files -- 
terminate called after throwing an instance of 'linuxdeploy::core::desktopfile::ParseError'
  what():  Key contains invalid character [
/bin/bash: line 83: 18702 Aborted                 (core dumped) LD_LIBRARY_PATH=$(pwd)/AppDir/usr/lib/x86_64-linux-gnu/ linuxdeploy --appdir AppDir -d $(pwd)/AppDir/usr/share/applications/kicad.desktop --output appimage
ERROR: Job failed: exit code 1
```

The error refers to the following line:
https://github.com/KiCad/kicad-source-mirror/blob/157519d722cefbc98c7aea754dd4ecb6270e426d/resources/linux/mime/applications/kicad.desktop#L13
```
Comment[fr]=Suite logicielle de conception électronique
```

AFAIK keys can contain the `[` character in order to specify translations.

**Comment by antoniovazquezblanco** [comment]
The problem seems to have been introduced in https://github.com/linuxdeploy/linuxdeploy/commit/b43b04f69317eaa9b78aefb15b0aa22666774152#diff-06c9dbf9140557a8b3b8ba45a7e50b1f

**Comment by TheAssassin** [comment]
@antoniovazquezblanco thanks for looking into this, will fix the issue as soon as possible.
