### ISSUE TITLE
Run on distros < oldest Ubuntu LTS

### ISSUE THREAD

**Issue by kossebau** [linuxdeploy/linuxdeploy#65]
linuxdeploy-x86_64.AppImage as downloaded today does not run on CentOS 6.10 (docker container), seems to be missing matching glibc(xx)?

What I did:
```
mkdir linuxdeploy
cd linuxdeploy/
wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
chmod +x linuxdeploy-x86_64.AppImage 
./linuxdeploy-x86_64.AppImage --appimage-extract
squashfs-root/AppRun 
```
The invocation of `AppRun` yields only these error messages:
```
squashfs-root/AppRun: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by squashfs-root/AppRun)
squashfs-root/AppRun: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by squashfs-root/AppRun)
squashfs-root/AppRun: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by squashfs-root/AppRun)
squashfs-root/AppRun: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by squashfs-root/AppRun)
squashfs-root/AppRun: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by squashfs-root/AppRun)
squashfs-root/AppRun: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /linuxdeploy/squashfs-root/usr/bin/../lib/liblinuxdeploy_desktopfile.so)
squashfs-root/AppRun: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /linuxdeploy/squashfs-root/usr/bin/../lib/liblinuxdeploy_desktopfile.so)
squashfs-root/AppRun: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by /linuxdeploy/squashfs-root/usr/bin/../lib/liblinuxdeploy_desktopfile.so)
squashfs-root/AppRun: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /linuxdeploy/squashfs-root/usr/bin/../lib/libpng12.so.0)
squashfs-root/AppRun: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /linuxdeploy/squashfs-root/usr/bin/../lib/libjpeg.so.8)
```

Given CentOS 6 has EOL 30 Nov 2020, and CentOS is still recommended on some parts of the AppImage wiki as proper base for creating appimages, would be nice to have linuxdeploy also run there.

**Comment by TheAssassin** [comment]
I've successfully built linuxdeploy on CentOS 6 using [devtoolset-6](https://www.softwarecollections.org/en/scls/rhscl/devtoolset-6/). I was told a while ago that devtoolset somehow is able to link against the super old libstdc++ on CentOS 6 while still allowing for using C++ 11+ by linking some bits of C++ statically and using some parts of the system libstdc++.

I took the binaries built there, built an AppDir from them and moved it to a vanilla container, and linuxdeploy ran successfully there. Therefore, I think we will be able to provide CentOS 6 binaries.

**Comment by TheAssassin** [comment]
We now provide an experimental AppImage on the release page that was built on CentOS 6. It hasn't been tested very much so far (unit tests are run, but no acceptance/system tests are performed yet). @kossebau  please try that AppImage on CentOS 6 machines and report whether it works there. In fresh CentOS 6 containers on my computer, it works fine so far.

**Comment by TheAssassin** [comment]
The CentOS 6 AppImage seems to work fine as a fallback. All left to do is to build the AppImage plugin on CentOS 6, too (I guess we can just do that by default, it'll work anywhere then anyway), and bundle that.

**Comment by probonopd** [comment]
So it comes down to using "modern C++" means limited support for running on old distributions?

**Comment by TheAssassin** [comment]
> So it comes down to using "modern C++" means limited support for running on old distributions?

Clearly wrong, see https://github.com/linuxdeploy/linuxdeploy/issues/65#issuecomment-474923887. It's just a lot of work and not needed really any more, since anything but CentOS 6 is EOL now anyway... So not a priority to invest hours and hours to making builds on a non-CI-native distro. It's all explained above.

**Comment by TheAssassin** [comment]
We've started to build on CentOS 6.
