### ISSUE TITLE
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'

### ISSUE THREAD

**Issue by zilti** [linuxdeploy/linuxdeploy#69]
No matter what I try to do, it always crashes:

```
$ linuxdeploy --list-plugins
/usr/bin/AppImageLauncher: /usr/lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
linuxdeploy version 1-alpha (git commit ID ce6597f), Travis build 350 built on 2019-01-29 00:03:34 UTC
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::status: Input/output error: "/run/user/1000/appimagelauncherfs/0004.AppImage"
Abgebrochen (Speicherabzug geschrieben)
```

**Comment by TheAssassin** [comment]
Please try to close all currently open AppImages, and then restart AppImageLauncherFS by calling `systemctl --user restart appimagelauncherfs.service`.

Can you please tell me the uptime of your system? I have a feeling that AppImageLauncherFS gets buggy after a while. Can't tell why, though. Might easily be a FUSE limitation.

**Comment by zilti** [comment]
A restart works - until I've started an AppImage. Then it breaks again. Well, it's not linuxdeploy's fault then!
