### ISSUE TITLE
Python plugin(s)

### ISSUE THREAD

**Issue by TheAssassin** [linuxdeploy/linuxdeploy#7]
We should try to offer one or more Python plugin to bundle Python software in the AppDir format.

As there are multiple options to bundle Python software which are more or less successful with specific apps, I could imagine developing more than one of them. If one fails, one can try another one.

PyInstaller seems to be capable of bundling most "non-complex" apps (tried this myself today). It provides its own "one file executable" format, but also can create an "application directory". As AppImages are more widespread, especially for desktop software, we could use the latter option to bundle Python software into e.g., `AppDir/usr/pyinstaller`, then use some simple code to copy the packages into the right locations.

The question is whether we can ship a version of PyInstaller _with_ such a plugin, or should require installation in the user's Python environment (most likely a virtualenv).

Another option is to use miniconda to create a full-featured, virtualenv-like structure in `AppDir/usr/`. This way, a portable and well-tested Python environment will be available in the virtualenv. Also, Anaconda provide a lot of libraries as precompiled and portable packages, which can simply be installed through a commandline tool.

**Comment by TheAssassin** [comment]
I wrote a conda plugin yesterday: https://github.com/TheAssassin/linuxdeploy-plugin-conda

What it does:
  - creates conda environment in `usr/conda/` -> standardized, reproducible
  - adds user-specified conda channels using `conda` (optional)
  - installs user-specified conda packages using `conda` (optional)

Who might want to use it:
  - people who package their software as a conda package, and want to turn it into an AppImage (e.g., FreeCAD (https://github.com/looooo/freecad_conda_appimage), see also https://github.com/TheAssassin/linuxdeploy-plugin-conda/pull/1)
  - people who need a functional, relocatable and _working_ Python (3) environment in their AppDir, e.g., to provide some Python scripting, etc.

Current issues:
  - adds a lot of bloat, as it just "installs" everything using conda, keeping stuff that is clearly not needed
    - already removing some of that, but the list could surely be extended, e.g., to delete Python modules which are most likely not needed (e.g., `2to3`); see [this part of the script]( https://github.com/TheAssassin/linuxdeploy-plugin-conda/blob/a366ce89b0fe4901d735ffc19bfef3bac66dc71a/linuxdeploy-plugin-conda.sh#L96) for more information.

**Comment by azubieta** [comment]
I guess we should move your code upstream. And make it the 'default' plugin

**Comment by TheAssassin** [comment]
You're probably right. Even though it adds some bloat, it's easy to use and reliable.

**Comment by azubieta** [comment]
It would be easier to track it and maintain from here. Otherwise, people will not use it and your work will be lost.

**Comment by TheAssassin** [comment]
> Otherwise, people will not use it and your work will be lost.

I highly doubt that, as it's listed here: https://github.com/linuxdeploy/awesome-linuxdeploy

However, I already promised to move it.

**Comment by TheAssassin** [comment]
Moved the repository. Closing this as resolved.
