### ISSUE TITLE
Add option to not strip binaries

### ISSUE THREAD

**Issue by ndarilek** [linuxdeploy/linuxdeploy#72]
I'm [distributing a game written with the Love2D framework](https://love2d.org/wiki/Game_Distribution). One suggested mechanism for distribution is to zip up all scripts and assets, then do something like:

```bash
$ cat /usr/bin/love game.zip >mygame
$ chmod +x mygame
```

to produce a single, mostly self-contained binary.

I couldn't figure out why my binaries worked just fine when I created them, but failed in the appdir and appimage. Turns out linuxdeploy is stripping them, which removes everything that makes my game my game. :)

Can we please have an option to not strip binaries? I'm working around this for now by creating a custom launcher and packaging my archive alongside the binary. But even though it only offers a small amount of protection, I'd like to go back to catting the archive onto the engine if I can.

Thanks.

**Comment by TheAssassin** [comment]
Like with all options, we can add an environment variable. We use env vars, as they're easy to use and also easy to pick up by subprocesses (e.g., plugins, which are in fact standalone tools).

`export NO_STRIP=1`, for instance? Any better naming suggestions?

**Comment by ndarilek** [comment]
No, and that works for me. Thanks!

**Comment by TheAssassin** [comment]
Actually, there already _is_ ``NO_STRIP`. Funny. Welp, in that case, I was quicker than I thought. Closing as resolved.

**Comment by wrosecrans** [comment]
It might be helpful to document NO_STRIP in the --help output.  I ran into a similar issue today and since --help doesn't mention any environment variables that would effect the behavior, I didn't understand that I would need to look elsewhere.  At least a note with a URL of a page that documents them?

**Comment by TheAssassin** [comment]
I agree that we have a lack of documentation here. I'll see what I can do. Maybe a `--list-env-vars` option or something.

**Comment by phoerious** [comment]
@TheAssassin Could this option be documented somewhere please? I suspected there was such a setting somewhere, but it took quite a bit of googling and searching linuxdeploy's source code to find it. A command line flag would be event better.

**Comment by phoerious** [comment]
I don't really see where it would fit in the README. There is no mention of any options whatsoever. A sentence in the `--help` printout would be more meaningful I suppose.

**Comment by TheAssassin** [comment]
Please open a new issue.
