### ISSUE TITLE
exclude libGLdispatch and libGLX

### ISSUE THREAD

**Issue by farindk** [linuxdeploy/linuxdeploy#89]
I think the following two libraries should be added to the excludelist:
    libGLdispatch.so.0
    libGLX.so.0

I have a Qt application that uses `QOpenGLContext`. When building the appimage with `linuxdeploy` and the qt plugin, this pulls in the above two libraries. I'm building this on Ubuntu 18.04. When started under Fedora (tested in VirtualBox), the OpenGL functions used don't seem to fit optimally to the system. It seems that I just get some fallback implementation (no OpenGL 3). Removing the above two libraries fixes this.

**Comment by TheAssassin** [comment]
You're right, these shouldn't be bundled. The problem originates in #83. But these files should be ignored anyway.

I'm going to add them to the excludelist in https://github.com/AppImage/pkg2appimage, and will rebuild all linuxdeploy software. This is going to take a moment, so please be a little patient. I'll update the issue one it's done.

**Comment by farindk** [comment]
Thanks, but no hurry, I patched it myself, quick and dirty, to get it working for me.

BTW, what I noticed: I modified the excludelist in `linuxdeploy` and compiled it myself, but when I was using the official qt plugin, it still pulled in those two libraries. Not sure whether that qt plugin is using the same excludelist.

**Comment by TheAssassin** [comment]
It doesn't fetch the excludelist from the main linuxdeploy binary. Internally it uses the same code base as linuxdeploy, which means that if you build it, the build pulls in the excludelist for it separately.

**Comment by TheAssassin** [comment]
Fixed in both linuxdeploy and the Qt plugin.

**Comment by farindk** [comment]
Thanks for the quick fix

**Comment by probonopd** [comment]
Looking at https://packages.ubuntu.com/search?suite=xenial&arch=any&searchon=contents&keywords=libGLX.so.0 it seems that libGLX.so.0 is specifically related to Nvidia. Shouldn't an application avoid depending on it in the first place?

**Comment by farindk** [comment]
@probonopd As far as I understand it, libGLX is vendor specific. Depending on your graphics driver, you'll have a different libGLX. The application is also usually not depending on libGLX directly, but through some other library.
However, that dependency must be somehow dynamic at runtime, as `lddtree` tells me that I don't have any libGLX dependency. That's where my knowledge ends :-)
