### ISSUE TITLE
Output file name

### ISSUE THREAD

**Issue by alexzk1** [linuxdeploy/linuxdeploy#90]
It makes output name based on "Name" field of .desktop file. However it is supposed to be long reading string for humans and may contain not allowed characters on FS.
Can you add option to explicit name output binary ?

**Comment by TheAssassin** [comment]
If you're using the (bundled) AppImage plugin, there's the `OUTPUT` environment variable. See https://github.com/linuxdeploy/linuxdeploy-plugin-appimage#optional-variables.
