### ISSUE TITLE
relocation error: ./linuxdeploy-x86_64.AppImage: symbol not defined

### ISSUE THREAD

**Issue by bugwelle** [linuxdeploy/linuxdeploy#91]
Hi,

just saw this in my latest build log on TravisCI:

```
./linuxdeploy-x86_64.AppImage: relocation error: ./linuxdeploy-x86_64.AppImage: symbol _ZTTNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
```

Did something change recently / during the last month, i.e. did I simply forget to adapt my deploy-script? :smiley:  
Haven't debugged it thoroughly as I assume that it's just a simple "did you update XYZ" issue.

Log: https://travis-ci.org/Komet/MediaElch/jobs/581292163#L2109  

Build step:  
https://github.com/Komet/MediaElch/blob/387e76168c1b6d1312adbb3104f02ff01e3a3f0a/travis-ci/package.sh#L167-L171

`.travis.yml`:  
https://github.com/Komet/MediaElch/blob/387e76168c1b6d1312adbb3104f02ff01e3a3f0a/.travis.yml#L94-L108

The Travis image uses Ubuntu 14.04. I use two plugins: `checkrt` and `qt`.

Regards,
Andre

**Comment by TheAssassin** [comment]
Ubuntu trusty is EOL. You shouldn't use it. We also don't support it any more, we build on xenial. Same goes for the Qt plugin.

Please change your Travis script to include `dist: xenial`.

**Comment by bugwelle** [comment]
Thanks. Thought it would be something like that. My builds only stopped being deployed about a month ago, though. 

Please also note that https://docs.appimage.org/packaging-guide/distribution.html still says that AppImages must support Ubuntu 14.04 though it's not supported anymore since April 2019.
Strangely the README of appimage.github.io is correct: 
https://github.com/AppImage/appimage.github.io/blob/e1c99de2d9a259641cd280b04518846f7a5884ea/README.md

I've opened https://github.com/AppImage/docs.appimage.org/issues/33

I'll update my deployment script and will close this issue if everything works :)

**Comment by bugwelle** [comment]
Updated Qt from 5.10 to 5.12 while I was at it. The resulting AppImage is now about 5MB larger but that's fine (probably because of Qt).

~~Seems like I'll have to debug something. The AppImage works when I build it locally on Kubuntu 18.04.
The one generated on TravisCI (Ubuntu 16.04) does run on Kubuntu 18.04 but doesn't run on my virtual machine (Ubuntu 16.04).  
That's more likely an issue on my side than in linuxdeployqt.~~

Changes: https://github.com/Komet/MediaElch/pull/780

~~I'll look into this. I had a similar issue once before. Don't know what helped, though..~~

I remember now. Updating helped... Don't know what was wrong with my machine but a simply `sudo apt update && sudo apt upgrade` helped. It works very well.

Works. Thank you for keeping linuxdeploy(-plugin-qt) up-to-date. :+1:
