### ISSUE TITLE
Why 2 x86_64 builds?

### ISSUE THREAD

**Issue by probonopd** [linuxdeploy/linuxdeploy#92]
Why are there 2 x86_64 builds?

Reference:
https://discourse.appimage.org/t/linuxdeploy-fails-to-run-on-fresh-ubuntu-14-04-solved/1400/2

**Comment by TheAssassin** [comment]
Search helps: https://github.com/linuxdeploy/linuxdeploy/issues/65#issuecomment-506968400. I don't have time to maintain builds for CentOS 6.

**Comment by probonopd** [comment]
The CentOS 6 build is the only one that works on trusty... so are you saying this won't run on trusty anymore?

**Comment by TheAssassin** [comment]
trusty has been EOL for months now. Noone should build on it any more. The only viable distro to support that is sufficiently old is CentOS 6, it's virtually the *only* old distribution, and it's not for desktops. AppImages should be built on xenial. And I don't consider CentOS support a priority. 

Please continue discussion in #65, this issue has been closed as duplicate.
