### ISSUE TITLE
ERROR: Could not find dependency: ../lib/libtbb.so.2 

### ISSUE THREAD

**Issue by probonopd** [linuxdeploy/linuxdeploy#93]
https://discourse.appimage.org/t/could-not-find-dependency/1388

> When running `linuxdeploy-x86_64.AppImage --appdir AppDir --output appimage`
> 
> I get the following error message:

    -- Deploying dependencies for existing files in AppDir -- 
    Deploying dependencies for ELF file AppDir/usr/bin/myapp
    ERROR: Could not find dependency: ../lib/libtbb.so.2 
    ERROR: Failed to deploy dependencies for existing files 

> where ../lib/libtbb.so.2 is a dependency of libembree.so.2 which is itself a dependency of myapp.
> 
> I think that as ../lib/libtbb.so.2 is not an absolute path, the shared lib is not found by linuxdeploy system (libtbb.so.2 is well present in AppDir/usr/lib).
> 
> Do you have a workaround for that ? Something that may help linuxdeploy find the libtbb.so.2 ?

**Comment by TheAssassin** [comment]
Please send them right here. I don't want anyone to play message relay. I don't provide support on any forums.

**Comment by TheAssassin** [comment]
And I won't conduct any deeper investigation this way.

**Comment by probonopd** [comment]
Done.

**Comment by goeland86** [comment]
I am running into a similar issue.
We're using linuxdeploy and we have a few 3rd-party libraries which are loaded at runtime if necessary.
There's a sequence of files, but essentially the difficulty seems to be an interdependency between the .so files.

```Deploying shared library builds/App-Desktop_Qt_5_15_2_GCC_64bit-Release/Setup/App/App/lib/liblcs2dll.so
>>> Deploying dependencies for ELF file builds/App-Desktop_Qt_5_15_2_GCC_64bit-Release/Setup/App/App/lib/liblcs2dll.so 
>>> ERROR: Could not find dependency: libutils.so 
>>> ERROR: Failed to deploy library:  builds/App-Desktop_Qt_5_15_2_GCC_64bit-Release/Setup/App/App/lib/liblcs2dll.so 
>>> >>> 
```

Any idea what could be causing this? In this case we absolutely do not want to load these .so files into the binary if they're not needed, but I can't build the AppImage with them in this way. I'm specifically passing in each of the 9 .so files with a `--library` parameter to the command-line.

**Comment by TheAssassin** [comment]
You should open a new issue. I'll respond then.

**Comment by TheAssassin** [comment]
Closing this as unresolved since the user from Discourse never showed up.
