### ISSUE TITLE
Difficult to find download/build instructions

### ISSUE THREAD

**Issue by thatch45** [linuxdeploy/linuxdeploy#97]
as I look over available documentation I am struggling to find a location to download an existing build or how to build from source.
How do I get linuxdeploy, so I can use it?

**Comment by TheAssassin** [comment]
You can download it from the release page. Check out https://docs.appimage.org/packaging-guide/from-source/linuxdeploy-user-guide.html.

**Comment by iTrooz** [comment]
I think It might be worth it to include a section in the README to tell the user to look there. I had to search for this issue to find out I had to go to releases
